export const GENERAL_KNOWLEDGE_QUESTION_BANK = [
  {
    id: 'gk-official-2026-fermentation', moduleId: 'general_knowledge', subjectId: 'technology', topicId: 'technology:biology',
    knowledgePointIds: ['technology:microorganisms'], stem: '国考2026年考试大纲常识例题考查传统酿造过程。以下哪项最能解释发酵环节的关键作用？',
    options: [{ id: 'A', text: '微生物参与底物代谢并产生相应产物' }, { id: 'B', text: '原料在密闭条件下自动变成金属' }, { id: 'C', text: '只有水分蒸发，不发生物质变化' }, { id: 'D', text: '必须由阳光直接提供全部反应物' }],
    correctAnswer: 'A', explanation: '发酵依赖微生物代谢。本站用短题意重述官方大纲例题的知识点，不复刻原题题面。', difficulty: 'easy',
    sourceType: 'official_outline_example', sourceId: 'gwy-2026-outline', sourceTitle: '2026年考试大纲常识判断例题（题意重述）',
    sourceNote: '按官方大纲公开例题所考的发酵与微生物知识改写；不是正式考试真题。', region: 'national', examYear: 2026,
    verificationStatus: 'verified', copyrightStatus: 'adapted_public_source', publishStatus: 'published', presentationMode: 'adapted',
  },
  {
    id: 'gk-official-2026-history', moduleId: 'general_knowledge', subjectId: 'history', topicId: 'history:modern',
    knowledgePointIds: ['history:revolutionary-period'], stem: '2026年官方考试大纲公布的常识例题以历史事件对应为考法。与1949年4月人民解放军占领南京这一事件相符的是哪项？',
    options: [{ id: 'A', text: '南京解放，国民党政权在大陆的统治结束' }, { id: 'B', text: '辛亥革命爆发' }, { id: 'C', text: '五四运动发生' }, { id: 'D', text: '抗日战争全面爆发' }],
    correctAnswer: 'A', explanation: '这是官方大纲例题所对应历史事实的题意重述。题目属于大纲例题改写，不是1949年原始试题。', difficulty: 'easy',
    sourceType: 'official_outline_example', sourceId: 'gwy-2026-outline', sourceTitle: '2026年考试大纲常识判断例题（题意重述）',
    sourceNote: '根据官方大纲公开历史例题及其解析重述，不展示原诗句或完整原题。', region: 'national', examYear: 2026,
    verificationStatus: 'verified', copyrightStatus: 'adapted_public_source', publishStatus: 'published', presentationMode: 'adapted',
  },
  {
    id: 'gk-official-2026-reaction', moduleId: 'general_knowledge', subjectId: 'technology', topicId: 'technology:chemistry',
    knowledgePointIds: ['technology:reactions'], stem: '2026年官方大纲常识例题区分了石灰石高温制取二氧化碳的反应类型。该反应属于哪一类？',
    options: [{ id: 'A', text: '分解反应' }, { id: 'B', text: '复分解反应' }, { id: 'C', text: '置换反应' }, { id: 'D', text: '化合反应' }],
    correctAnswer: 'A', explanation: '一种化合物受热生成多种物质，属于分解反应。本站对官方大纲例题作简短改写。', difficulty: 'easy',
    sourceType: 'official_outline_example', sourceId: 'gwy-2026-outline', sourceTitle: '2026年考试大纲常识判断例题（题意重述）',
    sourceNote: '根据官方大纲常识例题涉及的反应类型重述；不是正式考试真题。', region: 'national', examYear: 2026,
    verificationStatus: 'verified', copyrightStatus: 'adapted_public_source', publishStatus: 'published', presentationMode: 'adapted',
  },
  {
    id: 'gk-original-beijing-12345', moduleId: 'general_knowledge', subjectId: 'beijing', topicId: 'beijing:city-governance',
    knowledgePointIds: ['beijing:12345-response'], stem: '按照《北京市接诉即办工作条例》所述机制，接诉即办工作主要包括哪组环节？',
    options: [{ id: 'A', text: '快速响应、高效办理、及时反馈、主动治理' }, { id: 'B', text: '只收集诉求，不进行办理和反馈' }, { id: 'C', text: '由热线平台代替所有承办单位作出决定' }, { id: 'D', text: '只在年度总结时统一处理诉求' }],
    correctAnswer: 'A', explanation: '条例将接诉即办概括为快速响应、高效办理、及时反馈和主动治理。具体诉求仍由依法承担职责的单位办理。', difficulty: 'easy',
    sourceType: 'original', sourceId: 'beijing-12345-regulation', sourceTitle: '依据北京市接诉即办工作条例自编',
    sourceNote: '该练习题由本站根据官方条例概念自编，不冒充考试原题。', region: 'beijing', examYear: null,
    verificationStatus: 'verified', copyrightStatus: 'original', publishStatus: 'published', validAsOf: '2026-10-09',
  },
  {
    id: 'gk-original-opportunity-cost', moduleId: 'general_knowledge', subjectId: 'economy', topicId: 'economy:basics',
    knowledgePointIds: ['economy:opportunity-cost'], stem: '某人选择参加培训，因此放弃了当晚最有价值的一项兼职收入。评价这一选择时，机会成本最接近哪项？',
    options: [{ id: 'A', text: '被放弃的最佳替代方案的价值' }, { id: 'B', text: '所有未选择活动价值之和' }, { id: 'C', text: '以前已经支付且无法收回的费用' }, { id: 'D', text: '培训机构的全部营业收入' }],
    correctAnswer: 'A', explanation: '机会成本是放弃的可选方案中价值最高者。沉没成本是过去已发生且无法收回的费用。', difficulty: 'easy',
    sourceType: 'original', sourceId: 'economics-intro-reference', sourceTitle: '本站原创基础概念练习',
    sourceNote: '公开题源中未找到可确认展示授权的同考点题目，按基础经济学概念自编。', region: 'general', examYear: null,
    verificationStatus: 'verified', copyrightStatus: 'original', publishStatus: 'published',
  },
  {
    id: 'gk-original-law-separation', moduleId: 'general_knowledge', subjectId: 'law', topicId: 'law:administrative-law',
    knowledgePointIds: ['law:administrative-penalty'], stem: '某行政机关拟对违法行为作出处罚。下列哪项最符合依法行政的基本要求？',
    options: [{ id: 'A', text: '有法定依据，并按法定程序查明事实后作出决定' }, { id: 'B', text: '为提高效率，可以不告知当事人任何情况' }, { id: 'C', text: '行政机关可以自行创设任何处罚种类' }, { id: 'D', text: '事实证据不清时先处罚再补证' }],
    correctAnswer: 'A', explanation: '行政处罚须有法定依据并依程序实施；事实不清、证据不足时不得作出处罚决定。此题考查稳定的行政法原则，具体条款须查询现行法律文本。', difficulty: 'medium',
    sourceType: 'original', sourceId: 'npc-law-database', sourceTitle: '依据国家法律法规数据库公开法规自编',
    sourceNote: '本站自编通用原则练习，不复刻培训题库；具体条文请以数据库现行文本为准。', region: 'general', examYear: null,
    verificationStatus: 'verified', copyrightStatus: 'original', publishStatus: 'published', validAsOf: '2026-10-09',
  },
  {
    id: 'gk-original-rights', moduleId: 'general_knowledge', subjectId: 'law', topicId: 'law:constitution',
    knowledgePointIds: ['law:citizen-rights'], stem: '下列哪项最能体现我国宪法中劳动和受教育的双重属性？',
    options: [{ id: 'A', text: '二者既是公民权利，也属于公民义务' }, { id: 'B', text: '二者均只是一种可以任意转让的财产权' }, { id: 'C', text: '二者只适用于国家机关工作人员' }, { id: 'D', text: '二者不受任何法律规则调整' }],
    correctAnswer: 'A', explanation: '宪法规定劳动和受教育既是公民的权利，也是公民的义务。', difficulty: 'easy',
    sourceType: 'original', sourceId: 'npc-constitution', sourceTitle: '依据宪法公开条文自编',
    sourceNote: '本站根据官方宪法条文自编，不冒充考试真题。', region: 'general', examYear: null,
    verificationStatus: 'verified', copyrightStatus: 'original', publishStatus: 'published',
  },
  {
    id: 'gk-original-admin-minor-correction', moduleId: 'general_knowledge', subjectId: 'law', topicId: 'law:administrative-law',
    knowledgePointIds: ['law:administrative-penalty'], stem: '某经营者的违法行为情节轻微，发现后及时改正，且没有造成危害后果。依照《行政处罚法》，下列处理正确的是？',
    options: [{ id: 'A', text: '应当不予行政处罚，但依法仍应进行教育' }, { id: 'B', text: '可以不查明事实，直接从轻处罚' }, { id: 'C', text: '只有初次违法时才必须不予处罚' }, { id: 'D', text: '须先申请听证，才能不予处罚' }],
    correctAnswer: 'A', explanation: '《行政处罚法》第三十三条第一款规定，违法行为轻微并及时改正、没有造成危害后果的，不予行政处罚；该条还要求对依法不予处罚的当事人进行教育。', difficulty: 'easy',
    sourceType: 'original', sourceId: 'admin-penalty-law-2021', sourceTitle: '依据2021年修订《行政处罚法》第三十三条自编',
    sourceNote: '本站根据工信部政府门户发布的法规全文编写原创情境题，不是历年真题。', region: 'general', examYear: null,
    verificationStatus: 'verified', copyrightStatus: 'original', publishStatus: 'published', validAsOf: '2026-10-09',
  },
  {
    id: 'gk-original-admin-first-violation', moduleId: 'general_knowledge', subjectId: 'law', topicId: 'law:administrative-law',
    knowledgePointIds: ['law:administrative-penalty'], stem: '某单位初次发生违法行为，危害后果轻微，并已及时改正。关于行政机关能否不予处罚，正确的是？',
    options: [{ id: 'A', text: '符合条件就一律应当不予处罚' }, { id: 'B', text: '可以不予行政处罚' }, { id: 'C', text: '只能改为行政强制措施' }, { id: 'D', text: '必须处以罚款，不得裁量' }],
    correctAnswer: 'B', explanation: '《行政处罚法》第三十三条第二款使用“可以不予行政处罚”，与第一款满足条件时“不予行政处罚”的规定不同；题目中的“初次违法”不能单独推出必须免罚。', difficulty: 'medium',
    sourceType: 'original', sourceId: 'admin-penalty-law-2021', sourceTitle: '依据2021年修订《行政处罚法》第三十三条自编',
    sourceNote: '本站根据工信部政府门户发布的法规全文编写原创辨析题，不是历年真题。', region: 'general', examYear: null,
    verificationStatus: 'verified', copyrightStatus: 'original', publishStatus: 'published', validAsOf: '2026-10-09',
  },
  {
    id: 'gk-original-admin-hearing-rights', moduleId: 'general_knowledge', subjectId: 'law', topicId: 'law:administrative-law',
    knowledgePointIds: ['law:administrative-penalty'], stem: '行政机关拟对当事人作出行政处罚，当事人提交了陈述、申辩和相关证据。下列做法符合《行政处罚法》的是？',
    options: [{ id: 'A', text: '事前告知拟处罚内容、事实、理由、依据和相关权利，并听取、复核当事人的意见和证据' }, { id: 'B', text: '只要拟处罚事实已告知，就可以不审查当事人新提交的证据' }, { id: 'C', text: '当事人提出申辩的，可以据此加重处罚' }, { id: 'D', text: '先作出处罚决定，再补告知和听取意见' }],
    correctAnswer: 'A', explanation: '第四十四条要求在作出处罚决定前告知拟处罚内容及事实、理由、依据和相关权利；第四十五条要求充分听取陈述申辩、复核相关事实和证据，成立的应予采纳，且不得因当事人陈述申辩而给予更重处罚。第六十二条对违反上述告知、听取要求的决定作了限制。', difficulty: 'medium',
    sourceType: 'original', sourceId: 'admin-penalty-law-2021', sourceTitle: '依据2021年修订《行政处罚法》第四十四、四十五、六十二条自编',
    sourceNote: '本站根据工信部政府门户发布的法规全文编写原创程序辨析题，不是历年真题。', region: 'general', examYear: null,
    verificationStatus: 'verified', copyrightStatus: 'original', publishStatus: 'published', validAsOf: '2026-10-09',
  },
  {
    id: 'gk-original-review-deadline', moduleId: 'general_knowledge', subjectId: 'law', topicId: 'law:administrative-law',
    knowledgePointIds: ['law:administrative-remedies'], stem: '法律没有另行规定更长期限时，公民通常应在知道或者应当知道行政行为之日起多少日内提出行政复议申请？',
    options: [{ id: 'A', text: '三十日' }, { id: 'B', text: '六十日' }, { id: 'C', text: '九十日' }, { id: 'D', text: '六个月' }],
    correctAnswer: 'B', explanation: '2023年修订的《行政复议法》第二十条规定，通常的申请期限为知道或者应当知道行政行为之日起六十日；法律规定期限超过六十日的除外。不可抗力或其他正当理由耽误期限的，障碍消除后继续计算。', difficulty: 'easy',
    sourceType: 'original', sourceId: 'admin-reconsideration-law-2023', sourceTitle: '依据2023年修订《行政复议法》第二十条自编',
    sourceNote: '本站根据中国人大网原文（生态环境部转载）编写原创练习题，不是历年真题。', region: 'general', examYear: null,
    verificationStatus: 'verified', copyrightStatus: 'original', publishStatus: 'published', validAsOf: '2026-10-09',
  },
  {
    id: 'gk-original-review-prerequisite', moduleId: 'general_knowledge', subjectId: 'law', topicId: 'law:administrative-law',
    knowledgePointIds: ['law:administrative-remedies'], stem: '当事人不服行政机关当场作出的行政处罚决定，依照现行《行政复议法》通常应如何寻求救济？',
    options: [{ id: 'A', text: '先申请行政复议；对复议决定不服的，再依法提起行政诉讼' }, { id: 'B', text: '必须先申请行政调解，再决定是否复议' }, { id: 'C', text: '只能申请行政复议，之后不得提起行政诉讼' }, { id: 'D', text: '可以直接起诉，是否复议由行政机关决定' }],
    correctAnswer: 'A', explanation: '《行政复议法》第二十三条将不服当场作出的行政处罚决定列为复议前置情形：先申请行政复议；对复议决定不服的，可以依法向人民法院提起行政诉讼。', difficulty: 'medium',
    sourceType: 'original', sourceId: 'admin-reconsideration-law-2023', sourceTitle: '依据2023年修订《行政复议法》第二十三条自编',
    sourceNote: '本站根据中国人大网原文（生态环境部转载）编写原创程序辨析题，不是历年真题。', region: 'general', examYear: null,
    verificationStatus: 'verified', copyrightStatus: 'original', publishStatus: 'published', validAsOf: '2026-10-09',
  },
  {
    id: 'gk-original-review-oral-application', moduleId: 'general_knowledge', subjectId: 'law', topicId: 'law:administrative-law',
    knowledgePointIds: ['law:administrative-remedies'], stem: '申请人书面提交行政复议申请确有困难时，依照《行政复议法》可以采用哪种方式？',
    options: [{ id: 'A', text: '口头申请，由行政复议机构记录法定事项' }, { id: 'B', text: '只能请律师代为书面申请' }, { id: 'C', text: '向人民法院口头申请行政复议' }, { id: 'D', text: '先申请行政调解，调解不成后才可提出复议申请' }],
    correctAnswer: 'A', explanation: '《行政复议法》第二十二条允许书面申请；书面申请有困难的，也可以口头申请。行政复议机构应记录申请人的基本情况、复议请求、主要事实、理由和时间。', difficulty: 'easy',
    sourceType: 'original', sourceId: 'admin-reconsideration-law-2023', sourceTitle: '依据2023年修订《行政复议法》第二十二条自编',
    sourceNote: '本站根据中国人大网原文（生态环境部转载）编写原创程序辨析题，不是历年真题。', region: 'general', examYear: null,
    verificationStatus: 'verified', copyrightStatus: 'original', publishStatus: 'published', validAsOf: '2026-10-09',
  },
  {
    id: 'gk-original-ballastless-track', moduleId: 'general_knowledge', subjectId: 'technology', topicId: 'technology:physics',
    knowledgePointIds: ['technology:railway-track'], stem: '关于高速铁路常见的无砟轨道，下列说法正确的是？',
    options: [{ id: 'A', text: '以轨道板等结构承托钢轨，具有较好的稳定性和平顺性' }, { id: 'B', text: '轨道结构中必须铺满松散碎石道砟' }, { id: 'C', text: '不需要路基、桥梁等线下基础配合' }, { id: 'D', text: '钢轨直接铺在普通道路表面即可' }],
    correctAnswer: 'A', explanation: '无砟轨道采用轨道板等结构替代散粒道砟。国家铁路局资料介绍了高速铁路无砟轨道结构及其稳定、平顺、耐久等特点；轨道结构仍需与路基、桥梁等基础系统匹配。', difficulty: 'medium',
    sourceType: 'original', sourceId: 'railway-high-speed-design', sourceTitle: '依据国家铁路局高速铁路设计资料自编',
    sourceNote: '独立编写的知识点练习，承接搜集索引中的高速铁路轨道技术考点，不复刻原卷题面。', region: 'general', examYear: null,
    verificationStatus: 'verified', copyrightStatus: 'original', publishStatus: 'published', validAsOf: '2026-10-09',
  },
  {
    id: 'gk-original-lunar-eclipse', moduleId: 'general_knowledge', subjectId: 'geography', topicId: 'geography:natural',
    knowledgePointIds: ['geography:eclipse'], stem: '月全食期间，月面常呈暗红色或古铜色，主要原因是？',
    options: [{ id: 'A', text: '月球内部发光并穿过地球阴影' }, { id: 'B', text: '地球大气折射部分红光进入本影并照到月面' }, { id: 'C', text: '太阳停止发光，月面自行升温' }, { id: 'D', text: '月球进入太阳表面并反射红色火焰' }],
    correctAnswer: 'B', explanation: '地球处在太阳和月球之间时，地球大气会折射部分阳光进入本影；短波长光较易被散射，剩余红色光照到月面，形成暗红或古铜色外观。', difficulty: 'easy',
    sourceType: 'original', sourceId: 'lunar-eclipse-science', sourceTitle: '依据中国科学院紫金山天文台科普资料自编',
    sourceNote: '独立编写的知识点练习，参考搜集索引中的月全食考点，不复制回忆题面。', region: 'general', examYear: null,
    verificationStatus: 'verified', copyrightStatus: 'original', publishStatus: 'published', validAsOf: '2026-10-09',
  },
  {
    id: 'gk-original-thermal-printing', moduleId: 'general_knowledge', subjectId: 'technology', topicId: 'technology:information',
    knowledgePointIds: ['technology:thermal-printing'], stem: '超市小票使用热敏纸打印文字时，文字形成的关键过程是？',
    options: [{ id: 'A', text: '打印针逐点击打纸面留下凹痕' }, { id: 'B', text: '喷墨喷头将颜料液滴喷到普通纸上' }, { id: 'C', text: '打印头加热局部热敏涂层，使其显色' }, { id: 'D', text: '激光把纸张表面直接切开' }],
    correctAnswer: 'C', explanation: '热敏纸表面有热敏涂层，打印头对特定位置加热后，涂层中的显色体系发生变化形成文字，不依靠针头击打或喷墨。', difficulty: 'easy',
    sourceType: 'original', sourceId: 'thermal-printing-science', sourceTitle: '依据政府科普资料自编',
    sourceNote: '独立编写的知识点练习，承接搜集索引中的小票打印技术考点，不采用原题面。', region: 'general', examYear: null,
    verificationStatus: 'verified', copyrightStatus: 'original', publishStatus: 'published', validAsOf: '2026-10-09',
  },
];
