export const GENERAL_KNOWLEDGE_QUESTION_BANK = [
  {
    id: 'gk-official-2026-fermentation', moduleId: 'general_knowledge', subjectId: 'technology', topicId: 'technology:biology',
    knowledgePointIds: ['technology:microorganisms'], stem: '国考2026年考试大纲常识例题考查传统酿造过程。以下哪项最能解释发酵环节的关键作用？',
    options: [{ id: 'A', text: '微生物参与底物代谢并产生相应产物' }, { id: 'B', text: '原料在密闭条件下自动变成金属' }, { id: 'C', text: '只有水分蒸发，不发生物质变化' }, { id: 'D', text: '必须由阳光直接提供全部反应物' }],
    correctAnswer: 'A', explanation: '发酵依赖微生物代谢。本站用短题意重述官方大纲例题的知识点，不复刻原题题面。', difficulty: 'easy',
    sourceType: 'official_outline_example', sourceId: 'gwy-2026-outline', sourceTitle: '2026年考试大纲常识判断例题（题意重述）',
    sourceNote: '按官方大纲公开例题所考的发酵与微生物知识改写；不是正式考试真题。', region: 'national', examYear: 2026,
    verificationStatus: 'verified', copyrightStatus: 'adapted_public_source', publishStatus: 'published', presentationMode: 'adapted',
  },
  {
    id: 'gk-official-2026-history', moduleId: 'general_knowledge', subjectId: 'history', topicId: 'history:modern',
    knowledgePointIds: ['history:revolutionary-period'], stem: '2026年官方考试大纲公布的常识例题以历史事件对应为考法。与1949年4月人民解放军占领南京这一事件相符的是哪项？',
    options: [{ id: 'A', text: '南京解放，国民党政权在大陆的统治结束' }, { id: 'B', text: '辛亥革命爆发' }, { id: 'C', text: '五四运动发生' }, { id: 'D', text: '抗日战争全面爆发' }],
    correctAnswer: 'A', explanation: '这是官方大纲例题所对应历史事实的题意重述。题目属于大纲例题改写，不是1949年原始试题。', difficulty: 'easy',
    sourceType: 'official_outline_example', sourceId: 'gwy-2026-outline', sourceTitle: '2026年考试大纲常识判断例题（题意重述）',
    sourceNote: '根据官方大纲公开历史例题及其解析重述，不展示原诗句或完整原题。', region: 'national', examYear: 2026,
    verificationStatus: 'verified', copyrightStatus: 'adapted_public_source', publishStatus: 'published', presentationMode: 'adapted',
  },
  {
    id: 'gk-official-2026-reaction', moduleId: 'general_knowledge', subjectId: 'technology', topicId: 'technology:chemistry',
    knowledgePointIds: ['technology:reactions'], stem: '2026年官方大纲常识例题区分了石灰石高温制取二氧化碳的反应类型。该反应属于哪一类？',
    options: [{ id: 'A', text: '分解反应' }, { id: 'B', text: '复分解反应' }, { id: 'C', text: '置换反应' }, { id: 'D', text: '化合反应' }],
    correctAnswer: 'A', explanation: '一种化合物受热生成多种物质，属于分解反应。本站对官方大纲例题作简短改写。', difficulty: 'easy',
    sourceType: 'official_outline_example', sourceId: 'gwy-2026-outline', sourceTitle: '2026年考试大纲常识判断例题（题意重述）',
    sourceNote: '根据官方大纲常识例题涉及的反应类型重述；不是正式考试真题。', region: 'national', examYear: 2026,
    verificationStatus: 'verified', copyrightStatus: 'adapted_public_source', publishStatus: 'published', presentationMode: 'adapted',
  },
  {
    id: 'gk-original-beijing-12345', moduleId: 'general_knowledge', subjectId: 'beijing', topicId: 'beijing:city-governance',
    knowledgePointIds: ['beijing:12345-response'], stem: '按照《北京市接诉即办工作条例》所述机制，接诉即办工作主要包括哪组环节？',
    options: [{ id: 'A', text: '快速响应、高效办理、及时反馈、主动治理' }, { id: 'B', text: '只收集诉求，不进行办理和反馈' }, { id: 'C', text: '由热线平台代替所有承办单位作出决定' }, { id: 'D', text: '只在年度总结时统一处理诉求' }],
    correctAnswer: 'A', explanation: '条例将接诉即办概括为快速响应、高效办理、及时反馈和主动治理。具体诉求仍由依法承担职责的单位办理。', difficulty: 'easy',
    sourceType: 'original', sourceId: 'beijing-12345-regulation', sourceTitle: '依据北京市接诉即办工作条例自编',
    sourceNote: '该练习题由本站根据官方条例概念自编，不冒充考试原题。', region: 'beijing', examYear: null,
    verificationStatus: 'verified', copyrightStatus: 'original', publishStatus: 'published', validAsOf: '2026-10-09',
  },
  {
    id: 'gk-original-opportunity-cost', moduleId: 'general_knowledge', subjectId: 'economy', topicId: 'economy:basics',
    knowledgePointIds: ['economy:opportunity-cost'], stem: '某人选择参加培训，因此放弃了当晚最有价值的一项兼职收入。评价这一选择时，机会成本最接近哪项？',
    options: [{ id: 'A', text: '被放弃的最佳替代方案的价值' }, { id: 'B', text: '所有未选择活动价值之和' }, { id: 'C', text: '以前已经支付且无法收回的费用' }, { id: 'D', text: '培训机构的全部营业收入' }],
    correctAnswer: 'A', explanation: '机会成本是放弃的可选方案中价值最高者。沉没成本是过去已发生且无法收回的费用。', difficulty: 'easy',
    sourceType: 'original', sourceId: 'economics-intro-reference', sourceTitle: '本站原创基础概念练习',
    sourceNote: '公开题源中未找到可确认展示授权的同考点题目，按基础经济学概念自编。', region: 'general', examYear: null,
    verificationStatus: 'verified', copyrightStatus: 'original', publishStatus: 'published',
  },
  {
    id: 'gk-original-law-separation', moduleId: 'general_knowledge', subjectId: 'law', topicId: 'law:administrative-law',
    knowledgePointIds: ['law:administrative-penalty'], stem: '某行政机关拟对违法行为作出处罚。下列哪项最符合依法行政的基本要求？',
    options: [{ id: 'A', text: '有法定依据，并按法定程序查明事实后作出决定' }, { id: 'B', text: '为提高效率，可以不告知当事人任何情况' }, { id: 'C', text: '行政机关可以自行创设任何处罚种类' }, { id: 'D', text: '事实证据不清时先处罚再补证' }],
    correctAnswer: 'A', explanation: '行政处罚须有法定依据并依程序实施；事实不清、证据不足时不得作出处罚决定。此题考查稳定的行政法原则，具体条款须查询现行法律文本。', difficulty: 'medium',
    sourceType: 'original', sourceId: 'npc-law-database', sourceTitle: '依据国家法律法规数据库公开法规自编',
    sourceNote: '本站自编通用原则练习，不复刻培训题库；具体条文请以数据库现行文本为准。', region: 'general', examYear: null,
    verificationStatus: 'verified', copyrightStatus: 'original', publishStatus: 'published', validAsOf: '2026-10-09',
  },
  {
    id: 'gk-original-rights', moduleId: 'general_knowledge', subjectId: 'law', topicId: 'law:constitution',
    knowledgePointIds: ['law:citizen-rights'], stem: '下列哪项最能体现我国宪法中劳动和受教育的双重属性？',
    options: [{ id: 'A', text: '二者既是公民权利，也属于公民义务' }, { id: 'B', text: '二者均只是一种可以任意转让的财产权' }, { id: 'C', text: '二者只适用于国家机关工作人员' }, { id: 'D', text: '二者不受任何法律规则调整' }],
    correctAnswer: 'A', explanation: '宪法规定劳动和受教育既是公民的权利，也是公民的义务。', difficulty: 'easy',
    sourceType: 'original', sourceId: 'npc-constitution', sourceTitle: '依据宪法公开条文自编',
    sourceNote: '本站根据官方宪法条文自编，不冒充考试真题。', region: 'general', examYear: null,
    verificationStatus: 'verified', copyrightStatus: 'original', publishStatus: 'published',
  },
];
