export const GENERAL_KNOWLEDGE_SOURCES = [
  {
    id: 'gwy-2026-outline', sourceType: 'official_outline_example', title: '中央机关及其直属机构2026年度考试录用公务员公共科目笔试考试大纲',
    organization: '国家公务员局（国家林业和草原局政府网转载）', examYear: 2026,
    url: 'https://www.forestry.gov.cn/c/www/gsgg/645383.jhtml', verificationStatus: 'verified',
    publishStatus: 'published', copyrightStatus: '题意重述；不复制长题干',
    note: '大纲将常识判断列为独立部分，并公开三道常识例题。题目在本站以短题意重述呈现，不标为正式真题。',
  },
  {
    id: 'beijing-2026-outline', sourceType: 'official_outline_example', title: '北京市各级机关2026年度考试录用公务员公共科目笔试考试大纲（官方例题）',
    organization: '北京市公务员局 / 北京市人民政府', examYear: 2026,
    url: 'https://www.beijing.gov.cn/gongkai/rsxx/gwyzk/202511/P020251110416492086501.pdf', verificationStatus: 'verified',
    publishStatus: 'reference_only', copyrightStatus: '题面展示授权待核验',
    note: '题面、选项与答案已对照官方大纲核验；该来源可供核对，不代表已取得题面转载或公开练习许可。',
  },
  {
    id: 'npc-civil-code', sourceType: 'official_law', title: '中华人民共和国民法典', organization: '全国人民代表大会 / 国家法律法规数据库',
    url: 'https://flk.npc.gov.cn/detail2.html', verificationStatus: 'verified', publishStatus: 'published',
    copyrightStatus: '法规事实摘述并链接原文', note: '涉及具体法律条文时以国家法律法规数据库的有效文本为准。',
  },
  {
    id: 'npc-constitution', sourceType: 'official_law', title: '中华人民共和国宪法', organization: '全国人民代表大会 / 国家法律法规数据库',
    url: 'https://flk.npc.gov.cn/detail2.html', verificationStatus: 'verified', publishStatus: 'published',
    copyrightStatus: '法规事实摘述并链接原文', note: '用于公民权利义务知识；引用时核对现行有效版本。',
  },
  {
    id: 'npc-law-database', sourceType: 'official_law', title: '国家法律法规数据库', organization: '全国人大常委会办公厅',
    url: 'https://flk.npc.gov.cn/', verificationStatus: 'verified', publishStatus: 'published',
    copyrightStatus: '法规事实摘述并链接原文', note: '法律时效核验主入口。题库不替代对最新法律文本的查询。',
  },
  {
    id: 'railway-high-speed-design', sourceType: 'official_reference', title: '《高速铁路设计规范》专家解读', organization: '国家铁路局',
    url: 'https://source.nra.gov.cn/xxgk/gkml/ztjg/gfzd/zcjd/202204/t20220405_280609.shtml',
    verificationStatus: 'verified', publishStatus: 'published', copyrightStatus: '技术事实概述并链接原文',
    note: '国家铁路局说明高速铁路规范中的无砟轨道结构、轨道稳定性和平顺性要求；题目为本站独立编写。',
  },
  {
    id: 'lunar-eclipse-science', sourceType: 'official_reference', title: '月全食与“红月亮”', organization: '中国科学院紫金山天文台',
    url: 'https://pmo.cas.cn/xwdt2019/kpdt2019/201909/t20190915_5385983.html',
    verificationStatus: 'verified', publishStatus: 'published', copyrightStatus: '科学事实概述并链接原文',
    note: '紫金山天文台解释月全食期间地球大气折射长波段光进入本影，月面呈微红或古铜色。',
  },
  {
    id: 'thermal-printing-science', sourceType: 'official_reference', title: '热敏纸显色原理', organization: '江华瑶族自治县科学技术协会 / 县人民政府',
    url: 'https://jh.gov.cn/jh/kpjh/202411/494c6fff7e1c41b8a7671a4517ec0f11.shtml',
    verificationStatus: 'verified', publishStatus: 'published', copyrightStatus: '科学事实概述并链接原文',
    note: '政府科普页面介绍热敏涂层受热后的显色反应；题目为本站独立编写，不采用原题面。',
  },
  {
    id: 'admin-penalty-law-2021', sourceType: 'official_law', title: '中华人民共和国行政处罚法（2021年修订）', organization: '工业和信息化部政府门户网站',
    url: 'https://www.miit.gov.cn/zwgk/zcwj/flfg/art/2022/art_76d37c09bd594d67b80ec2aa6fababcc.html',
    verificationStatus: 'verified', publishStatus: 'published', copyrightStatus: '法规事实摘述并链接法规全文',
    note: '官方全文载明2021年修订文本及第三十三、第四十四、第四十五、第六十二条；2021年7月15日起施行。',
  },
  {
    id: 'admin-reconsideration-law-2023', sourceType: 'official_law', title: '中华人民共和国行政复议法（2023年修订）', organization: '中国人大网原文（生态环境部转载）',
    url: 'https://www.mee.gov.cn/home/ztbd/2022/sthjpf/fgbzjd/202309/t20230914_1040873.shtml',
    verificationStatus: 'verified', publishStatus: 'published', copyrightStatus: '法规事实摘述并链接法规全文',
    note: '全国人大原文转载；2023年9月1日修订、2024年1月1日起施行，第二十条规定通常的六十日申请期限及例外。',
  },
  {
    id: 'beijing-12345-regulation', sourceType: 'official_policy', title: '北京市接诉即办工作条例', organization: '北京市人民代表大会常务委员会 / 首都之窗',
    url: 'https://www.beijing.gov.cn/zhengce/dfxfg/202109/t20210925_2501573.html', verificationStatus: 'verified',
    publishStatus: 'published', copyrightStatus: '法规事实摘述并链接原文', note: '政府门户页面标示本条例自2021-09-24施行、现行有效；使用前仍需复核状态。',
  },
  {
    id: 'gov-2026-work-report', sourceType: 'official_policy', title: '2026年政府工作报告', organization: '国务院',
    url: 'https://www.gov.cn/yaowen/liebiao/202603/content_7062625.htm',
    verificationStatus: 'verified', publishStatus: 'published', copyrightStatus: '政策事实概述并链接原文',
    note: '时政内容保留年度标签；该条只表示报告资料来源，不代表下一年度仍适用。',
  },
  {
    id: 'beijing-master-plan', sourceType: 'official_policy', title: '北京城市总体规划与城市空间资料', organization: '北京市人民政府',
    url: 'https://www.beijing.gov.cn/', verificationStatus: 'pending', publishStatus: 'reference_only',
    copyrightStatus: '待定位具体现行规划文本', note: '当前仅作后续核对入口；相应知识点不作为已核验的空间细节题。',
  },
  {
    id: 'mmee-carbon-neutral', sourceType: 'official_policy', title: '碳达峰碳中和与生态环境公开资料', organization: '生态环境部',
    url: 'https://www.mee.gov.cn/', verificationStatus: 'pending', publishStatus: 'reference_only',
    copyrightStatus: '待定位具体政策/技术文本', note: '目录入口，后续发布具体双碳数据前须定位正式文件。',
  },
  {
    id: 'stats-cpi', sourceType: 'official_statistics', title: '国家统计局居民消费价格指数资料', organization: '国家统计局',
    url: 'https://www.stats.gov.cn/', verificationStatus: 'pending', publishStatus: 'reference_only',
    copyrightStatus: '统计口径待逐题标注', note: '知识讲解说明CPI概念，不使用未核验的年度数值。',
  },
  {
    id: 'unesco-solar-terms', sourceType: 'official_reference', title: '二十四节气（人类非物质文化遗产）', organization: '联合国教科文组织',
    url: 'https://ich.unesco.org/en/RL/knowledge-of-the-times-and-practices-concerning-the-twenty-four-solar-terms-00647',
    verificationStatus: 'verified', publishStatus: 'published', copyrightStatus: '事实概述并链接原文',
    note: '用于节气的文化遗产身份与基础解释，不复用第三方题库题干。',
  },
  {
    id: 'gov-ai-guidance', sourceType: 'official_reference', title: '人工智能与数据治理公开政策索引', organization: '国家互联网信息办公室',
    url: 'https://www.cac.gov.cn/', verificationStatus: 'pending', publishStatus: 'reference_only',
    copyrightStatus: '待定位具体现行文件', note: '未定位具体文件前只讲稳定基础概念，不发布法规时效判断。',
  },
  {
    id: 'party-history-public', sourceType: 'official_reference', title: '中国共产党历史和改革开放权威资料索引', organization: '中共中央党史和文献研究院',
    url: 'https://www.dswxyjy.org.cn/', verificationStatus: 'pending', publishStatus: 'reference_only',
    copyrightStatus: '待定位具体资料条目', note: '仅作内容核对入口；不发布未经逐项核实的具体时间题。',
  },
  {
    id: 'economics-intro-reference', sourceType: 'official_reference', title: '基础经济学术语参考索引', organization: '本站编写团队',
    url: 'https://www.stats.gov.cn/', verificationStatus: 'reviewed', publishStatus: 'published',
    copyrightStatus: '本站原创讲解', note: '用于稳定的基础经济学概念；不包含特定年度统计数据。',
  },
  {
    id: 'marxism-public-reference', sourceType: 'official_reference', title: '马克思主义哲学基础公开学习资料索引', organization: '中国社会科学院 / 公开理论资料',
    url: 'https://www.cssn.cn/', verificationStatus: 'pending', publishStatus: 'reference_only',
    copyrightStatus: '待定位具体出处', note: '索引入口；相关理论简述仍需补充具体权威材料和逐条复核。',
  },
  {
    id: 'offcn-public-mock-index', sourceType: 'third_party_mock', title: '中公教育公开模拟题页面（来源索引）', organization: '中公教育',
    url: 'https://xzgwy.offcn.com/2020/xc_0526/25734_7.html', verificationStatus: 'reviewed',
    publishStatus: 'reference_only', copyrightStatus: '题面展示授权未核实',
    note: '页面可访问不等于获得复制授权。暂不收录其题干，后续仅在取得授权或确认许可后作为练习题。',
  },
  {
    id: 'gaodun-shanghai-mock-index', sourceType: 'third_party_mock', title: '高顿公考上海市考模拟卷页面（来源索引）', organization: '高顿公考',
    url: 'https://gk.gaodun.com/shanghai/gongwuyuan/xingce/1540.html', verificationStatus: 'reviewed',
    publishStatus: 'reference_only', copyrightStatus: '题面展示授权未核实',
    note: '作为后续真题类型和题源调查索引，不将网页可访问误作题目开放许可。',
  },
  {
    id: 'anhui-2026-outline', sourceType: 'official_outline_example', title: '安徽省2026年度公务员笔试考试大纲（公开例题）', organization: '安徽省人力资源和社会保障厅 / 淮南市人力资源和社会保障局',
    url: 'https://rsj.huainan.gov.cn/group4/M00/11/14/rB40qWlooVmAFWHRAA3nByKSHRA495.pdf?attachDownload=1', verificationStatus: 'verified',
    publishStatus: 'published', copyrightStatus: '例题摘要改写并链接官方大纲', note: '覆盖政治理论、常识判断、言语、数量、判断推理和资料分析公开例题；图片题因图像未随文字抽取而未纳入。',
  },
  {
    id: 'zhejiang-2025a-recall', sourceType: 'recalled', title: '2025年浙江省公务员考试《行测》A类回忆版及答案', organization: '公开真题库 / 考生回忆资料',
    url: 'https://gwy.gkzhenti.cn/paper/1739531137130', answerUrl: 'https://gwy.gkzhenti.cn/answer/1739531137130', verificationStatus: 'verified',
    publishStatus: 'published', copyrightStatus: '题意与选项摘要改写并注明回忆来源', note: '仅发布题面资源完整、答案可核的分项；Q12依赖未取得的路线图，继续暂缓。公开答案页用于核对答案，不代表官方命题文件。',
  },
  {
    id: 'hubei-2024-recall-candidate', sourceType: 'recalled', title: '2024年湖北省公务员录用考试《行测》题（考生回忆版）', organization: '爱真题 / 湖北网 / ERRRC 公开题解', examYear: 2024, region: '湖北',
    url: 'https://www.aipta.com/article/9625.html',
    answerUrl: 'https://www.163hubei.com/ueditor/php/upload/file/20240318/1710751920689656.pdf', verificationStatus: 'verified',
    publishStatus: 'published', copyrightStatus: '用户确认已获得转载授权',
    note: '题面来自公开考生回忆版；答案按湖北网公开参考答案、解析按公开题解核对。题面与答案解析齐全且无未解决冲突的82题已接入；含图题及答案冲突项留档待核。',
  },
  {
    id: 'henan-2026-recall', sourceType: 'recalled', title: '2026年河南省公务员录用考试《行测》题（网友回忆版）', organization: '公开真题库 / 考生回忆资料', examYear: 2026, region: '河南',
    url: 'https://gwy.gkzhenti.cn/paper/1775360735848', answerUrl: 'https://gwy.gkzhenti.cn/answer/1775360735848', verificationStatus: 'verified',
    publishStatus: 'published', copyrightStatus: '用户确认已获得转载授权', note: '仅将题面、答案和解析完整的题目接入对应模块；河南常识第91–105题已核对，整卷及缺项题暂不开放。',
  },
  {
    id: 'national-2025-deputy-recall', sourceType: 'recalled', title: '2025年国家公务员录用考试《行测》题（副省级网友回忆版）', organization: '公开真题库 / 考生回忆资料 / ERRRC公开题解', examYear: 2025, region: '国考',
    url: 'https://gwy.gkzhenti.cn/paper/1735356969686', answerUrl: 'https://gwy.gkzhenti.cn/answer/1735356969686', verificationStatus: 'verified',
    publishStatus: 'published', copyrightStatus: '用户确认已获得转载授权', note: '政治理论、常识判断、言语理解、数量关系、判断推理和资料分析共135题均已按原题号接入；题解来自第三方公开整理，答案与公开答案页逐题核对。',
  },
  {
    id: 'mofcom-emergency-supplies', sourceType: 'official_policy', title: '生活必需品市场供应应急管理相关规定', organization: '中华人民共和国商务部',
    url: 'https://www.mofcom.gov.cn/zcfb/blgg/art/2011/art_9c44dbc882cd47a2a2db6ddd07e242fd.html', verificationStatus: 'verified', publishStatus: 'published',
    copyrightStatus: '政策事实概述并链接原文', note: '用于应急组织货源、储备投放和生活必需品市场供应管理的基础概念。',
  },
  {
    id: 'ndrc-three-distributions', sourceType: 'official_policy', title: '促进共同富裕与三次分配的政策解读', organization: '国家发展和改革委员会',
    url: 'https://www.ndrc.gov.cn/fggz/jyysr/jysrsbxf/202109/t20210924_1297384_ext.html', verificationStatus: 'verified', publishStatus: 'published',
    copyrightStatus: '政策事实概述并链接原文', note: '用于区分初次分配、再分配和第三次分配的主体与机制。',
  },
  {
    id: 'npc-oath-decision', sourceType: 'official_law', title: '关于实行宪法宣誓制度的决定', organization: '全国人民代表大会常务委员会',
    url: 'https://www.npc.gov.cn/npc/c2/c30834/202306/t20230606_429893.html', verificationStatus: 'verified', publishStatus: 'published',
    copyrightStatus: '法条事实摘述并链接原文', note: '宣誓适用对象和组织程序以现行法律决定为准。',
  },
  {
    id: 'court-judge-oath-rules', sourceType: 'official_law', title: '中华人民共和国法官宣誓组织办法', organization: '最高人民法院',
    url: 'https://www.court.gov.cn/fabu/xiangqing/20262.html', verificationStatus: 'verified', publishStatus: 'published',
    copyrightStatus: '规则事实摘述并链接原文', note: '用于核对法院系统法官职务宣誓的组织安排。',
  },
  {
    id: 'cpc-20th-report', sourceType: 'official_policy', title: '中国共产党第二十次全国代表大会报告', organization: '中国政府网',
    url: 'https://app.www.gov.cn/govdata/gov/202210/25/493662/article.html', verificationStatus: 'verified', publishStatus: 'published',
    copyrightStatus: '政策观点概述并链接原文', note: '用于核对城乡融合、发展与公平及生态文明等稳定政策表述。',
  },
  {
    id: 'beijing-willow-fluff', sourceType: 'official_reference', title: '杨柳飞絮与植物种子传播科普', organization: '北京市园林绿化局',
    url: 'https://yllhj.beijing.gov.cn/ztxx/zlylfxgcyjhj/ylfxqy/201510/t20151013_119733.shtml', verificationStatus: 'verified', publishStatus: 'published',
    copyrightStatus: '科学事实概述并链接原文', note: '说明杨柳飞絮与种子绒毛及风力传播之间的关系。',
  },
  {
    id: 'pku-capsaicin-chemistry', sourceType: 'official_reference', title: '辣椒素溶解性与生活化学实验研究', organization: '北京大学《大学化学》',
    url: 'https://www.dxhx.pku.edu.cn/fileup/1000-8438/PDF/dxhx-201803041.pdf', verificationStatus: 'verified', publishStatus: 'published',
    copyrightStatus: '科学事实概述并链接论文', note: '用于核对辣椒素在水、乙醇等介质中的溶解性。',
  },
  {
    id: 'nra-railway-track', sourceType: 'official_reference', title: '高速铁路设计规范专家解读', organization: '国家铁路局',
    url: 'https://source.nra.gov.cn/xxgk/gkml/ztjg/gfzd/zcjd/202204/t20220405_280609.shtml', verificationStatus: 'verified', publishStatus: 'published',
    copyrightStatus: '技术事实概述并链接原文', note: '用于高速铁路轨道结构与线路基础知识；无缝线路仍须考虑温度变化。',
  },
  {
    id: 'moe-employment-priority', sourceType: 'official_policy', title: '高校毕业生等青年就业服务与支持政策', organization: '教育部',
    url: 'https://www.moe.gov.cn/jyb_xxgk/moe_1777/moe_1778/202409/t20240926_1153200.html', verificationStatus: 'verified', publishStatus: 'published',
    copyrightStatus: '政策事实概述并链接原文', note: '用于就业服务、重点群体支持和技能提升等知识点。',
  },
  {
    id: 'mct-transaction-costs', sourceType: 'official_policy', title: '降低制度性交易成本相关政策解读', organization: '文化和旅游部转载国务院办公厅材料',
    url: 'https://www.mct.gov.cn/preview/whhlyqyzcxxfw/yshjxf/202306/t20230612_944383.html', verificationStatus: 'verified', publishStatus: 'published',
    copyrightStatus: '政策事实概述并链接原文', note: '用于区分制度规则及流程带来的成本与企业正常生产投入。',
  },
  {
    id: 'politburo-20240926', sourceType: 'official_policy', title: '中共中央政治局会议研究当前经济形势和经济工作', organization: '新华社',
    url: 'https://www.xinhuanet.com/fortune/20240926/0f9a6b9e501c48ea85aea3b6d8cc7ccc/c.html', verificationStatus: 'verified', publishStatus: 'published',
    copyrightStatus: '政策事实概述并链接原文', note: '用于核对2024年9月26日会议关于扩大内需、逆周期调节和民生工作的表述。',
  },
  {
    id: 'pbc-lpr', sourceType: 'official_reference', title: '贷款市场报价利率形成机制与公布资料', organization: '中国人民银行',
    url: 'https://www.pbc.gov.cn/zhengcehuobisi/125207/125213/125440/125832/2804873/index.html', verificationStatus: 'verified', publishStatus: 'published',
    copyrightStatus: '机制事实概述并链接原文', note: '用于LPR的报价、公布和贷款定价传导知识。',
  },
  {
    id: 'ethnic-autonomy-law', sourceType: 'official_law', title: '中华人民共和国民族区域自治法', organization: '司法部行政复议行政应诉局法规公开平台',
    url: 'https://xzfy.moj.gov.cn/c/2021-01-06/487588.shtml', verificationStatus: 'verified', publishStatus: 'published',
    copyrightStatus: '法条事实摘述并链接原文', note: '用于核对自治地方、自治机关及主要负责人的法定规定。',
  },
  {
    id: 'palace-history', sourceType: 'official_reference', title: '故宫博物院院史与紫禁城沿革', organization: '故宫博物院',
    url: 'https://www.dpm.org.cn/subject_600/index.html', verificationStatus: 'verified', publishStatus: 'published',
    copyrightStatus: '历史事实概述并链接原文', note: '用于核对紫禁城营建、明清皇宫及故宫博物院沿革。',
  },
  {
    id: 'most-salt-tolerant-rice', sourceType: 'official_reference', title: '耐盐碱水稻研究与示范应用', organization: '科学技术部',
    url: 'https://www.most.gov.cn/dfkj/hain/zxdt/202203/t20220323_179960.html', verificationStatus: 'verified', publishStatus: 'published',
    copyrightStatus: '科技事实概述并链接原文', note: '用于说明耐盐碱品种及其土壤、水分和栽培条件。',
  },
  {
    id: 'spacecraft-battery-upgrade', sourceType: 'official_reference', title: '神舟飞船储能电池技术升级', organization: '中国航天科技集团有限公司',
    url: 'https://www.spacechina.com/n25/n2014789/n2014809/c4217099/content.html', verificationStatus: 'verified', publishStatus: 'published',
    copyrightStatus: '科技事实概述并链接原文', note: '官方资料说明神舟十八号起主电源储能电池由镉镍体系改为锂离子体系。',
  },
  {
    id: 'hangzhou-2022-flame', sourceType: 'official_reference', title: '杭州亚运会火种采集于良渚古城遗址', organization: '杭州第19届亚运会组委会',
    url: 'https://www.hangzhou2022.cn/xwzx/jdxw/ttxw/202306/t20230615_62401.shtml', verificationStatus: 'verified', publishStatus: 'published',
    copyrightStatus: '事实概述并链接原文', note: '用于区分良渚遗址与河姆渡遗址及亚运会火种采集地点。',
  },
  {
    id: 'lantern-festival-poem', sourceType: 'official_reference', title: '元宵节诗词文本参考', organization: '中国哲学书电子化计划',
    url: 'https://ctext.org/text.pl?if=gb&node=208579', verificationStatus: 'reviewed', publishStatus: 'published',
    copyrightStatus: '古典作品出处并链接原文', note: '用于核对“正月中旬”“灯市”等诗词线索与元宵节的关系。',
  },
  {
    id: 'unesco-liangzhu', sourceType: 'official_reference', title: '良渚古城遗址世界遗产资料', organization: '联合国教科文组织世界遗产中心',
    url: 'https://whc.unesco.org/en/list/1592/', verificationStatus: 'verified', publishStatus: 'published',
    copyrightStatus: '遗产事实概述并链接原文', note: '用于核对良渚古城的考古、社会组织与世界遗产信息。',
  },
  {
    id: 'china-fire-gas-safety', sourceType: 'official_reference', title: '燃气泄漏时的家庭安全处置', organization: '国家消防救援局',
    url: 'https://www.119.gov.cn/kp/hzyf/jt/2022/1201.shtml', verificationStatus: 'verified', publishStatus: 'published',
    copyrightStatus: '安全事实概述并链接原文', note: '燃气泄漏时不要操作电器开关或产生火花，应按消防部门指引通风、撤离并求助。',
  },
  {
    id: 'beijing-political-consultation-regulation', sourceType: 'official_policy', title: '中国共产党政治协商工作条例', organization: '中共中央 / 首都之窗',
    url: 'https://www.beijing.gov.cn/zhengce/zhengcefagui/202206/t20220621_2747230.html', verificationStatus: 'verified', publishStatus: 'published',
    copyrightStatus: '政策规则概述并链接原文', note: '条例区分政党协商与人民政协政治协商，并列明两类协商的对象。',
  },
  {
    id: 'beijing-2023-recall', sourceType: 'recalled', title: '2023年北京市公务员录用考试《行测》真题（考生回忆版）',
    organization: '星光公考（题面回忆整理）；拉西学习资源站（答案解析，标注来源为1mi.xyz）', examYear: 2023, region: '北京',
    url: 'https://upload.xingguanggongkao.com/pdf/2023%E5%B9%B4%E5%8C%97%E4%BA%AC%E5%B8%82%E5%85%AC%E5%8A%A1%E5%91%98%E5%BD%95%E7%94%A8%E8%80%83%E8%AF%95%E3%80%8A%E8%A1%8C%E6%B5%8B%E3%80%8B%E7%9C%9F%E9%A2%98%EF%BC%88%E8%80%83%E7%94%9F%E5%9B%9E%E5%BF%86%E7%89%88%EF%BC%89.pdf?time=1733730281',
    answerUrl: 'https://lasee.net/gongwuyuan/167886579811619.html', verificationStatus: 'verified', publishStatus: 'published',
    copyrightStatus: 'adapted_public_source', note: '题面与答案分别由公开回忆 PDF 和答案解析页核验；本站仅发布题意改述的常识第1–14、16题。第15题缺失，整卷有缺题且非官方原卷。',
  },
  {
    id: 'moe-history-curriculum-2022', sourceType: 'official_reference', title: '义务教育历史课程标准（2022年版）', organization: '中华人民共和国教育部',
    url: 'https://www.moe.gov.cn/srcsite/A26/s8001/202204/W020220420582345700037.pdf', verificationStatus: 'verified', publishStatus: 'published',
    copyrightStatus: '课程范围与历史事实概述并链接原文', note: '用于历史时期、重大事件、制度与历史时序方法的基础核对。',
  },
  {
    id: 'cpc-history-volume-one', sourceType: 'official_reference', title: '中国共产党历史·第一卷（1921—1949）', organization: '中共中央党史和文献研究院 / 中共党史出版社',
    url: 'https://www.dswxyjy.org.cn/n1/2019/0627/c427919-31199220.html', verificationStatus: 'verified', publishStatus: 'published',
    copyrightStatus: '历史事实概述并链接权威出版资料', note: '用于鸦片战争以来近代史、辛亥革命、五四运动和中国共产党成立等时间线核对。',
  },
  {
    id: 'moe-chinese-textbook-intro', sourceType: 'official_reference', title: '普通高中语文教材介绍', organization: '中华人民共和国教育部',
    url: 'https://www.moe.gov.cn/fbh/live/2019/51084/sfcl/201908/t20190827_395974.html', verificationStatus: 'verified', publishStatus: 'published',
    copyrightStatus: '课程选文范围概述并链接原文', note: '用于古典诗文、文学体裁和中国文学史常见脉络的学习参考。',
  },
  {
    id: 'unesco-intangible-china', sourceType: 'official_reference', title: '中国非物质文化遗产名录条目', organization: '联合国教科文组织',
    url: 'https://ich.unesco.org/en/state/china-CN?info=elements-on-the-lists', verificationStatus: 'verified', publishStatus: 'published',
    copyrightStatus: '遗产项目事实概述并链接原文', note: '用于核对中国列入 UNESCO 非物质文化遗产名录的戏曲、节庆、书法和传统工艺项目。',
  },
  {
    id: 'unesco-ich-convention', sourceType: 'official_reference', title: '保护非物质文化遗产公约', organization: '联合国教科文组织',
    url: 'https://ich.unesco.org/en/convention', verificationStatus: 'verified', publishStatus: 'published',
    copyrightStatus: '公约定义与领域概述并链接原文', note: '用于非物质文化遗产的社区认定、代际传承、活态变化及主要领域。',
  },
  {
    id: 'unesco-peking-opera', sourceType: 'official_reference', title: '京剧（人类非物质文化遗产）', organization: '联合国教科文组织',
    url: 'https://ich.unesco.org/en/RL/peking-opera-00418', verificationStatus: 'verified', publishStatus: 'published',
    copyrightStatus: '艺术形式事实概述并链接原文', note: '用于京剧唱、念、做、打及象征性舞台表达等知识。',
  },
  {
    id: 'unesco-kunqu-opera', sourceType: 'official_reference', title: '昆曲（人类非物质文化遗产）', organization: '联合国教科文组织',
    url: 'https://ich.unesco.org/en/RL/kun-qu-opera-00004', verificationStatus: 'verified', publishStatus: 'published',
    copyrightStatus: '艺术形式事实概述并链接原文', note: '用于昆曲形成地域、历史时期和表演特点核对。',
  },
  {
    id: 'unesco-xuan-paper', sourceType: 'official_reference', title: '宣纸传统制作技艺（人类非物质文化遗产）', organization: '联合国教科文组织',
    url: 'https://ich.unesco.org/en/RL/traditional-handicrafts-of-making-xuan-paper-00201', verificationStatus: 'verified', publishStatus: 'published',
    copyrightStatus: '工艺事实概述并链接原文', note: '用于宣纸原料、产地、制作技艺和书画用途核对。',
  },
  {
    id: 'unesco-timber-craft', sourceType: 'official_reference', title: '中国传统木结构营造技艺', organization: '联合国教科文组织',
    url: 'https://ich.unesco.org/en/RL/chinese-traditional-architectural-craftsmanship-for-timber-framed-structures-00223', verificationStatus: 'verified', publishStatus: 'published',
    copyrightStatus: '建筑技艺事实概述并链接原文', note: '用于传统木结构建筑与营造技艺的活态传承知识。',
  },
  {
    id: 'unesco-world-heritage-faq', sourceType: 'official_reference', title: '世界遗产文化、自然与混合类别说明', organization: '联合国教科文组织世界遗产中心',
    url: 'https://whc.unesco.org/en/faq/319', verificationStatus: 'verified', publishStatus: 'published',
    copyrightStatus: '公约类别事实概述并链接原文', note: '用于区分文化遗产、自然遗产和兼具两类价值的混合遗产。',
  },
  {
    id: 'icom-museum-definition', sourceType: 'official_reference', title: '国际博物馆协会博物馆定义（2022）', organization: '国际博物馆协会',
    url: 'https://icom.museum/en/resources/standards-guidelines/museum-definition/', verificationStatus: 'verified', publishStatus: 'published',
    copyrightStatus: '机构定义概述并链接原文', note: '用于博物馆的研究、收藏、保护、诠释、展示与教育服务等职能。',
  },
  {
    id: 'met-art-history-education', sourceType: 'official_reference', title: '世界艺术史与宗教艺术教育资料', organization: '大都会艺术博物馆',
    url: 'https://resources.metmuseum.org/resources/metpublications/pdf/The_Art_of_South_and_Southeast_Asia_A_Resource_for_Educators.pdf', verificationStatus: 'verified', publishStatus: 'published',
    copyrightStatus: '艺术与宗教基础事实概述并链接教育资料', note: '用于世界艺术史、南亚宗教艺术及文化语境的基础学习。',
  },
  {
    id: 'met-renaissance-art', sourceType: 'official_reference', title: '文艺复兴欧洲艺术教育资料', organization: '大都会艺术博物馆',
    url: 'https://www.metmuseum.org/-/media/files/learn/for-educators/publications-for-educators/renaissance.pdf', verificationStatus: 'verified', publishStatus: 'published',
    copyrightStatus: '艺术史事实概述并链接原文', note: '用于文艺复兴时期欧洲艺术、人物与事件背景核对。',
  },
  {
    id: 'met-ancient-greece-art', sourceType: 'official_reference', title: '古希腊艺术史时间线', organization: '大都会艺术博物馆',
    url: 'https://www.metmuseum.org/pt/toah/ht/04/eusb', verificationStatus: 'verified', publishStatus: 'published',
    copyrightStatus: '艺术史事实概述并链接原文', note: '用于古希腊几何、古风、古典与希腊化时期艺术的时序核对。',
  },
  {
    id: 'met-world-religions', sourceType: 'official_reference', title: '南亚与东南亚宗教艺术教育资料', organization: '大都会艺术博物馆',
    url: 'https://resources.metmuseum.org/resources/metpublications/pdf/The_Art_of_South_and_Southeast_Asia_A_Resource_for_Educators.pdf', verificationStatus: 'verified', publishStatus: 'published',
    copyrightStatus: '宗教与艺术基础知识概述并链接教育资料', note: '用于印度教、佛教、耆那教与伊斯兰艺术的地域和文化语境参考。',
  },
  {
    id: 'moe-geography-curriculum-2022', sourceType: 'official_reference', title: '义务教育地理课程标准（2022年版）', organization: '中华人民共和国教育部',
    url: 'https://www.moe.gov.cn/srcsite/A26/s8001/202204/W020220420582354066450.pdf', verificationStatus: 'verified', publishStatus: 'published',
    copyrightStatus: '地理概念与课程事实概述并链接原文', note: '用于中国与世界地理、自然地理、资源、人口及区域认知方法的基础核对。',
  },
  {
    id: 'moe-biology-curriculum-2022', sourceType: 'official_reference', title: '义务教育生物学课程标准（2022年版）', organization: '中华人民共和国教育部',
    url: 'https://www.moe.gov.cn/srcsite/A26/s8001/202204/W020220420582359998122.pdf', verificationStatus: 'verified', publishStatus: 'published',
    copyrightStatus: '生态学基础概念概述并链接原文', note: '用于生态系统成分、食物关系、自我调节能力、生物多样性和生态保护的基础核对。',
  },
  {
    id: 'china-admin-divisions', sourceType: 'official_reference', title: '中国行政区划基本资料', organization: '中央人民政府驻香港特别行政区联络办公室（转载中国政府网资料）',
    url: 'https://www.locpg.gov.cn/2022-06/07/c_1211652713.htm', verificationStatus: 'verified', publishStatus: 'published',
    copyrightStatus: '行政区划知识概述并链接官方资料', note: '用于区分省级行政区类型与行政层级；具体数量和名称需按资料年份核对。',
  },
  {
    id: 'beijing-geography-official', sourceType: 'official_reference', title: '北京概况：区划、地形与气候', organization: '北京市人民政府',
    url: 'https://www.beijing.gov.cn/renwen/index.html', verificationStatus: 'verified', publishStatus: 'published',
    copyrightStatus: '地理事实概述并链接原文', note: '用于北京山地—平原格局、气候特点及现行行政区划资料核对。',
  },
  {
    id: 'beijing-rivers-resource', sourceType: 'official_reference', title: '北京市河流水系与水资源资料', organization: '北京市规划和自然资源委员会 / 北京市发展和改革委员会',
    url: 'https://ghzrzyw.beijing.gov.cn/biaozhunguanli/bzxg/202507/P020250711369794779987.pdf', verificationStatus: 'verified', publishStatus: 'published',
    copyrightStatus: '水系与水资源事实概述并链接原文', note: '用于核对北京河流水系、来水季节性及水资源空间差异。',
  },
  {
    id: 'beijing-water-planning', sourceType: 'official_policy', title: '北京市水资源保护与利用规划资料', organization: '北京市发展和改革委员会',
    url: 'https://fgw.beijing.gov.cn/fgwzwgk/2024zcwj/ghjhwb/wngh/202203/t20220303_3733060.htm', verificationStatus: 'verified', publishStatus: 'published',
    copyrightStatus: '规划事实概述并链接原文', note: '用于北京水资源保护、供需管理与节约利用的政策背景参考。',
  },
  {
    id: 'beijing-district-list', sourceType: 'official_reference', title: '北京市行政区划资料', organization: '北京市民政局',
    url: 'https://mzj.beijing.gov.cn/col/col9984/index.html', verificationStatus: 'verified', publishStatus: 'published',
    copyrightStatus: '区划事实概述并链接原文', note: '用于核对北京市现行区级行政区划；区名与代码变动时以民政部门更新为准。',
  },
  {
    id: 'mee-biodiversity-plan-2023', sourceType: 'official_policy', title: '中国生物多样性保护战略与行动计划（2023—2030年）', organization: '生态环境部',
    url: 'https://www.mee.gov.cn/xxgk/hjyw/202401/t20240118_1064111.shtml', verificationStatus: 'verified', publishStatus: 'published',
    copyrightStatus: '政策目标和生态事实概述并链接原文', note: '用于生物多样性保护、生态系统完整性及保护行动的知识点核对。',
  },
  {
    id: 'mee-solid-waste-guide', sourceType: 'official_reference', title: '固体废物资源化利用技术指南', organization: '中华人民共和国生态环境部',
    url: 'https://www.mee.gov.cn/ywgz/fgbz/bz/bzwb/jcffbz/202001/t20200115_759463.shtml', verificationStatus: 'verified', publishStatus: 'published',
    copyrightStatus: '环境治理概念概述并链接原文', note: '用于固体废物减量、资源化利用和规范处置的基础知识核对。',
  },
  {
    id: 'state-council-protected-areas', sourceType: 'official_policy', title: '关于建立以国家公园为主体的自然保护地体系的指导意见', organization: '中共中央办公厅、国务院办公厅（中国政府网公开）',
    url: 'https://app.www.gov.cn/govdata/gov/201906/26/444736/article.html', verificationStatus: 'verified', publishStatus: 'published',
    copyrightStatus: '政策类别和保护目标概述并链接原文', note: '用于理解国家公园、自然保护区、自然公园等保护地的功能定位；具体管理规定应核对现行法律政策。',
  },
  {
    id: 'state-council-waste-recycling', sourceType: 'official_policy', title: '加快构建废弃物循环利用体系的意见', organization: '国务院办公厅（生态环境部公开）',
    url: 'https://www.mee.gov.cn/zcwj/gwywj/202402/t20240220_1066422.shtml', verificationStatus: 'verified', publishStatus: 'published',
    copyrightStatus: '循环利用政策事实概述并链接原文', note: '用于理解废弃物减量化、资源化和循环利用之间的关系。',
  },
  {
    id: 'forestry-carbon-sink', sourceType: 'official_reference', title: '森林碳汇基础知识', organization: '国家林业和草原局',
    url: 'https://www.forestry.gov.cn/c/www/zhzs/655018.jhtml', verificationStatus: 'verified', publishStatus: 'published',
    copyrightStatus: '生态与碳汇事实概述并链接原文', note: '用于森林吸收和储存二氧化碳的基本原理；碳汇能力受生态条件和管理影响。',
  },
  {
    id: 'ipcc-ar6-synthesis', sourceType: 'official_reference', title: '气候变化2023：第六次评估综合报告', organization: '政府间气候变化专门委员会（IPCC）',
    url: 'https://www.ipcc.ch/report/ar6/syr/', verificationStatus: 'verified', publishStatus: 'published',
    copyrightStatus: '科学结论概述并链接报告', note: '用于温室气体、气候变化影响、减缓与适应的综合科学证据；具体评估结论应保留报告年份与置信度。',
  },
  {
    id: 'beijing-city-master-plan', sourceType: 'official_policy', title: '北京城市总体规划（2016年—2035年）', organization: '北京市人民政府',
    url: 'https://www.beijing.gov.cn/gongkai/guihua/wngh/csztgh/201907/t20190701_100008.html', verificationStatus: 'verified', publishStatus: 'published',
    copyrightStatus: '规划内容概述并链接原文', note: '用于首都战略定位、城市空间结构、中心城区、平原新城、生态涵养区和城市功能的知识点核对；规划实施情况应关注后续政策。',
  },
  {
    id: 'unesco-beijing-central-axis', sourceType: 'official_reference', title: '北京中轴线：展现中国理想都城秩序的建筑群', organization: '联合国教科文组织世界遗产中心',
    url: 'https://whc.unesco.org/en/list/1714/', verificationStatus: 'verified', publishStatus: 'published',
    copyrightStatus: '遗产价值和历史事实概述并链接原文', note: '世界遗产中心资料载明北京中轴线于2024年列入《世界遗产名录》，用于其空间格局、历史沿革和保护价值核对。',
  },
  {
    id: 'ndrc-jingjinji-coordination', sourceType: 'official_policy', title: '京津冀协同发展规划纲要与区域协调资料', organization: '国家发展和改革委员会',
    url: 'https://www.ndrc.gov.cn/gjzl/jjjxtfz/201911/t20191127_1213171.html', verificationStatus: 'verified', publishStatus: 'published',
    copyrightStatus: '区域发展政策事实概述并链接原文', note: '用于京津冀协同发展的战略背景、重点领域和非首都功能疏解等内容；阶段任务需按新文件更新。',
  },
  {
    id: 'beijing-street-office-regulation', sourceType: 'official_law', title: '北京市街道办事处条例', organization: '北京市人民代表大会常务委员会 / 首都之窗',
    url: 'https://www.beijing.gov.cn/zhengce/dfxfg/201912/t20191217_1243859.html', verificationStatus: 'verified', publishStatus: 'published',
    copyrightStatus: '法规内容摘要并链接原文', note: '用于街道办事处职责、基层公共服务和“街乡吹哨、部门报到”机制；使用前仍应核对条例当前有效状态。',
  },
  {
    id: 'beijing-public-culture-regulation', sourceType: 'official_law', title: '北京市公共文化服务保障条例', organization: '北京市人民代表大会常务委员会 / 首都之窗',
    url: 'https://www.beijing.gov.cn/zhengce/dfxfg/202210/t20221012_2833474.html', verificationStatus: 'verified', publishStatus: 'published',
    copyrightStatus: '法规内容摘要并链接原文', note: '用于公共文化服务主体、设施、基本服务和公众参与等知识点；条例自2023年1月1日起施行，使用前应复核现行状态。',
  },
  {
    id: 'beijing-science-center-regulation', sourceType: 'official_law', title: '北京国际科技创新中心建设条例', organization: '北京市人民代表大会常务委员会 / 首都之窗',
    url: 'https://www.beijing.gov.cn/zhengce/dfxfg/202401/t20240126_3547046.html', verificationStatus: 'verified', publishStatus: 'published',
    copyrightStatus: '法规内容摘要并链接原文', note: '用于北京科技创新中心的平台布局、创新主体协同和基础研究支持等知识点；使用前仍应核对法规状态。',
  },
  {
    id: 'beijing-urban-renewal-plan', sourceType: 'official_policy', title: '北京市城市更新专项规划', organization: '北京市发展和改革委员会 / 北京市规划和自然资源委员会',
    url: 'https://fgw.beijing.gov.cn/fgwzwgk/2024zcwj/ghjhwb/wngh/202206/W020240628680193553139.pdf', verificationStatus: 'verified', publishStatus: 'published',
    copyrightStatus: '规划内容概述并链接原文', note: '用于城市更新的空间统筹、存量提质、公共设施补充和历史文化保护协同。',
  },
  {
    id: 'beijing-subcenter-regulation-2026', sourceType: 'official_law', title: '北京城市副中心条例', organization: '北京市人民代表大会常务委员会 / 首都之窗',
    url: 'https://www.beijing.gov.cn/zhengce/dfxfg/202602/t20260203_4487890.html', verificationStatus: 'verified', publishStatus: 'published',
    copyrightStatus: '法规内容摘要并链接原文', note: '用于城市副中心空间结构、生产生活生态统筹和公共空间等知识点；法规事实按2026年官方页面核对。',
  },
  {
    id: 'beijing-transport-governance-2026', sourceType: 'official_policy', title: '2026年北京市交通综合治理行动计划', organization: '北京市人民政府',
    url: 'https://www.beijing.gov.cn/zhengce/zhengcefagui/202602/t20260202_4484508.html', verificationStatus: 'verified', publishStatus: 'published',
    copyrightStatus: '行动计划要点概述并链接原文', note: '用于公交与轨道接驳、慢行交通、绿色出行和综合治理知识点；目标数字均保留计划年份。',
  },
  {
    id: 'beijing-smart-city-action', sourceType: 'official_policy', title: '北京市“十四五”时期智慧城市发展行动纲要', organization: '北京市人民政府',
    url: 'https://www.beijing.gov.cn/zhengce/zhengcefagui/202103/t20210323_2317136.html', verificationStatus: 'verified', publishStatus: 'published',
    copyrightStatus: '规划概念摘要并链接原文', note: '用于“一网通办”“一网统管”等数字治理概念；该纲要属于“十四五”时期文件，后续阶段任务应以新规划为准。',
  },
  {
    id: 'moe-physics-experiments-2022', sourceType: 'official_reference', title: '初中物理实验教学基本目录解读', organization: '中华人民共和国教育部',
    url: 'https://www.moe.gov.cn/jyb_xwfb/moe_2082/2023/2023_zl24/202311/t20231123_1091839.html', verificationStatus: 'verified', publishStatus: 'published',
    copyrightStatus: '基础科学事实概述并链接原文', note: '教育部说明物理实验目录依据2022年版课程标准制定，包含测量、探究和能量转化等实验；用于物理生活常识基础核对。',
  },
  {
    id: 'moe-chemistry-curriculum-2022', sourceType: 'official_reference', title: '义务教育化学课程标准（2022年版）', organization: '中华人民共和国教育部',
    url: 'https://www.moe.gov.cn/srcsite/A26/s8001/202204/W020230605524875861384.pdf', verificationStatus: 'verified', publishStatus: 'published',
    copyrightStatus: '课程与科学事实概述并链接原文', note: '用于物质组成、化学变化、酸碱、溶液、实验探究和生活化学安全的基础核对。',
  },
  {
    id: 'moe-information-tech-curriculum-2022', sourceType: 'official_reference', title: '义务教育信息科技课程标准（2022年版）', organization: '中华人民共和国教育部',
    url: 'https://www.moe.gov.cn/srcsite/A26/s8001/202204/W020220420582361024968.pdf', verificationStatus: 'verified', publishStatus: 'published',
    copyrightStatus: '课程与技术事实概述并链接原文', note: '用于互联网组成、TCP/IP分层、数据编码传输、网络安全和信息社会责任的基础核对。',
  },
  {
    id: 'nhc-vaccine-science', sourceType: 'official_reference', title: '疫苗接种科普知识', organization: '中华人民共和国国家卫生健康委员会',
    url: 'https://www.nhc.gov.cn/wjw/jbyfykz/201604/e73973a39ece42fdba98e3d8a001acd7.shtml', verificationStatus: 'verified', publishStatus: 'published',
    copyrightStatus: '免疫原理概述并链接原文', note: '用于疫苗诱导特异性免疫反应的基础原理；接种程序和个体健康问题应核对现行卫生部门指南。',
  },
  {
    id: 'cmse-space-station-system', sourceType: 'official_reference', title: '中国空间站系统组成与运行分工', organization: '中国载人航天工程办公室',
    url: 'https://www.cmse.gov.cn/gygc/xtzc/kjzxt/', verificationStatus: 'verified', publishStatus: 'published',
    copyrightStatus: '工程组成事实概述并链接原文', note: '官方工程页面介绍空间站的多模块实验平台、航天员长期驻留以及载人飞船和货运飞船的任务分工。',
  },
  {
    id: 'cmse-space-station-orbit', sourceType: 'official_reference', title: '中国空间站轨道参数', organization: '中国载人航天工程办公室',
    url: 'https://www.cmse.gov.cn/gfgg/zgkjzgdcs/', verificationStatus: 'verified', publishStatus: 'published',
    copyrightStatus: '轨道参数查证入口并链接原文', note: '官方动态轨道参数发布页；具体数值随轨道控制变化，讲解只使用稳定的近地轨道概念。',
  },
  {
    id: 'cmse-crewed-launcher', sourceType: 'official_reference', title: '长征二号F运载火箭系统', organization: '中国载人航天工程办公室',
    url: 'https://www.cmse.gov.cn/gygc/xtzc/zzehfyzhjxt/', verificationStatus: 'verified', publishStatus: 'published',
    copyrightStatus: '运载任务事实概述并链接原文', note: '官方工程页面介绍长征二号F火箭用于发射载人飞船与实验室；具体任务型号应以当次任务公告为准。',
  },
  {
    id: 'cnsa-remote-sensing-science', sourceType: 'official_reference', title: '关于遥感卫星，你了解多少？', organization: '国家航天局',
    url: 'https://www.cnsa.gov.cn/n6758968/n6758973/c10560080/content.html', verificationStatus: 'verified', publishStatus: 'published',
    copyrightStatus: '技术原理概述并链接原文', note: '介绍遥感通过传感器接收远距离目标反射或辐射的电磁波信息，并经处理、反演和解译形成应用信息。',
  },
  {
    id: 'cac-ipv6-internet-basics', sourceType: 'official_reference', title: '中国IPv6进行时', organization: '中央网络安全和信息化委员会办公室',
    url: 'https://www.cac.gov.cn/2020-11/15/c_1607009489963634.htm', verificationStatus: 'verified', publishStatus: 'published',
    copyrightStatus: '互联网基础概念概述并链接原文', note: '用于IP地址在网络识别和数据传输中的作用，以及IPv4、IPv6地址空间差异的基础核对。',
  },
  {
    id: 'npc-network-security-law', sourceType: 'official_law', title: '中华人民共和国网络安全法（国家法律法规数据库）', organization: '全国人民代表大会常务委员会',
    url: 'https://flk.npc.gov.cn/detail?fileId=&id=2c909fdd678bf17901678bf8276f093d&title=%E4%B8%AD%E5%8D%8E%E4%BA%BA%E6%B0%91%E5%85%B1%E5%92%8C%E5%9B%BD%E7%BD%91%E7%BB%9C%E5%AE%89%E5%85%A8%E6%B3%95&type=', verificationStatus: 'verified', publishStatus: 'published',
    copyrightStatus: '法律框架概述并链接现行文本', note: '国家法律法规数据库的网络安全法条目；法律时效和关联修改文件应以数据库当前状态为准。',
  },
  {
    id: 'npc-data-security-law-2021', sourceType: 'official_law', title: '中华人民共和国数据安全法', organization: '全国人民代表大会常务委员会 / 国家法律法规数据库',
    url: 'https://flk.npc.gov.cn/detail?fileId=&id=ff80818179f5e0800179f885c7e70392&title=%E4%B8%AD%E5%8D%8E%E4%BA%BA%E6%B0%91%E5%85%B1%E5%92%8C%E5%9B%BD%E6%95%B0%E6%8D%AE%E5%AE%89%E5%85%A8%E6%B3%95&type=', verificationStatus: 'verified', publishStatus: 'published',
    copyrightStatus: '法律概念摘要并链接现行文本', note: '用于数据定义、处理活动和数据安全基本框架；具体义务依数据库标示的有效文本判断。',
  },
  {
    id: 'npc-personal-information-protection-law', sourceType: 'official_law', title: '中华人民共和国个人信息保护法', organization: '全国人民代表大会常务委员会 / 全国人大常委会公报',
    url: 'https://wb.flk.npc.gov.cn/flfg/PDF/f67af9f12e1b4c83a998cf5a876ce0e4.pdf', verificationStatus: 'verified', publishStatus: 'published',
    copyrightStatus: '法律概念摘要并链接公报原文', note: '用于个人信息权益、处理活动和敏感个人信息等基础概念；具体合规要求应核对现行法律法规。',
  },
  {
    id: 'nea-photovoltaic-principle', sourceType: 'official_reference', title: '名词解释：光伏发电', organization: '国家能源局',
    url: 'https://www.nea.gov.cn/2011-09/30/c_131169301.htm', verificationStatus: 'verified', publishStatus: 'published',
    copyrightStatus: '能量转换原理概述并链接原文', note: '国家能源局资料解释光伏电池利用半导体光电效应发电，并区分组件、逆变器和储能等系统环节。',
  },
  {
    id: 'miit-future-industries-2024', sourceType: 'official_policy', title: '工业和信息化部等七部门关于推动未来产业创新发展的实施意见', organization: '工业和信息化部等七部门',
    url: 'https://www.miit.gov.cn/zwgk/zcwj/wjfb/yj/art/2024/art_ad15b0f08a714fd8888c0e31468b8c54.html', verificationStatus: 'verified', publishStatus: 'published',
    copyrightStatus: '产业方向概述并链接政策原文', note: '文件按未来制造、未来信息、未来材料、未来能源、未来空间、未来健康等方向部署；只用于科技方向识别，不将规划目标当作既成事实。',
  },
  {
    id: 'miit-new-battery-plan-2026', sourceType: 'official_policy', title: '新型电池产业发展“十五五”规划解读', organization: '工业和信息化部等七部门',
    url: 'https://www.miit.gov.cn/zwgk/zcjd/art/2026/art_2d166bf3c90e45dfbdcd5fbaae9c9b17.html', verificationStatus: 'verified', publishStatus: 'published',
    copyrightStatus: '电池技术方向概述并链接政策原文', note: '用于锂电、钠电、液流电池等储能与电化学转换概念；规划中的阶段目标应保留年份和文件属性。',
  },
  {
    id: 'cas-synthetic-biology', sourceType: 'official_reference', title: '合成生物学学科战略研究', organization: '中国科学院学部 / 国家自然科学基金委员会',
    url: 'https://academics.casad.cas.cn/cbw/zgxkjqyly2035fzzlcs/hcswx/', verificationStatus: 'verified', publishStatus: 'published',
    copyrightStatus: '学科概念概述并链接原文', note: '介绍合成生物学将工程设计方法用于生命系统研究，涉及生物制造、健康、能源、环境和材料等交叉领域。',
  },
  {
    id: 'npc-criminal-law', sourceType: 'official_law', title: '中华人民共和国刑法（国家法律法规数据库）', organization: '全国人民代表大会 / 国家法律法规数据库',
    url: 'https://flk.npc.gov.cn/detail?fileId=&id=ff808181796a636a0179822a19640c92&title=&type=', verificationStatus: 'verified', publishStatus: 'published',
    copyrightStatus: '犯罪构成和法律关系摘要并链接现行文本', note: '国家法律法规数据库刑法条目；共同犯罪、财产犯罪和具体刑责均应按数据库当前有效文本核对。',
  },
  {
    id: 'samr-civil-servants-law-2018', sourceType: 'official_law', title: '中华人民共和国公务员法（2018年修订）', organization: '国家市场监督管理总局（官方全文转载）',
    url: 'https://www.samr.gov.cn/zw/zfxxgk/fdzdgknr/bgt/art/2023/art_6af2e9cf52224593b4dc15258bb34860.html', verificationStatus: 'verified', publishStatus: 'published',
    copyrightStatus: '法定义务和权利摘要并链接法规全文', note: '用于公务员义务、权利、依法履职和管理监督等基础知识；引用具体条文前应核对现行版本。',
  },
  {
    id: 'mee-ecological-environment-code-2026', sourceType: 'official_law', title: '中华人民共和国生态环境法典', organization: '全国人民代表大会 / 生态环境部',
    url: 'https://www.mee.gov.cn/ywgz/fgbz/fl/202603/t20260313_1146496.shtml', verificationStatus: 'verified', publishStatus: 'published',
    copyrightStatus: '法律原则摘要并链接法典全文', note: '法典于2026年3月12日通过、2026年8月15日起施行；用于生态环境治理原则、政府职责和公众参与等现行法知识核对。',
  },
  {
    id: 'beijing-city-renewal-regulation', sourceType: 'official_law', title: '北京市城市更新条例', organization: '北京市人民代表大会常务委员会 / 首都之窗',
    url: 'https://www.beijing.gov.cn/zhengce/dfxfg/202212/t20221206_2871600.html', verificationStatus: 'verified', publishStatus: 'published',
    copyrightStatus: '法规制度摘要并链接原文', note: '条例自2023年3月1日起施行；用于居住、产业、设施、公共空间和区域综合性更新分类及基层参与机制核对。',
  },
  {
    id: 'beijing-ecology-conservation-regulation', sourceType: 'official_law', title: '北京市生态涵养区生态保护和绿色发展条例', organization: '北京市人民代表大会常务委员会 / 首都之窗',
    url: 'https://www.beijing.gov.cn/zhengce/dfxfg/202104/t20210421_2365099.html', verificationStatus: 'verified', publishStatus: 'published',
    copyrightStatus: '法规空间与原则摘要并链接原文', note: '条例自2021年6月5日起施行；用于生态涵养区范围、生态优先、系统治理和绿色发展等北京地方知识核对。',
  },
  {
    id: 'moe-curriculum-2022', sourceType: 'official_reference', title: '义务教育课程方案和课程标准（2022年版）发布通知', organization: '中华人民共和国教育部',
    url: 'https://hudong.moe.gov.cn/srcsite/A26/s8001/202204/t20220420_619921.html', verificationStatus: 'verified', publishStatus: 'published',
    copyrightStatus: '课程目标与基础概念概述并链接原文', note: '用于科学探究、科学素养和义务教育课程范围的基础核对。',
  },
  {
    id: 'npc-social-insurance-law', sourceType: 'official_law', title: '中华人民共和国社会保险法', organization: '全国人民代表大会常务委员会 / 国家市场监督管理总局官方转载',
    url: 'https://www.samr.gov.cn/zw/zfxxgk/fdzdgknr/bgt/art/2023/art_e81d115419b4463ebb59ec46467fb136.html', verificationStatus: 'verified', publishStatus: 'published',
    copyrightStatus: '法律制度摘要并链接法规全文', note: '用于五项法定社会保险制度、参保缴费与待遇框架核对；具体经办规则以现行法规为准。',
  },
  {
    id: 'moj-social-assistance-law-2026', sourceType: 'official_law', title: '中华人民共和国社会救助法', organization: '司法部智慧普法平台 / 新华社',
    url: 'https://legalinfo.moj.gov.cn/zhfxfzzx/fzzxyw/202604/t20260430_534433.html', verificationStatus: 'verified', publishStatus: 'published',
    copyrightStatus: '法律框架摘要并链接官方发布信息', note: '2026年4月30日通过，2026年7月1日起施行；用于社会救助的法律框架和制度定位核对。',
  },
  {
    id: 'beijing-emergency-response-law-2024', sourceType: 'official_law', title: '中华人民共和国突发事件应对法（2024年修订）', organization: '北京市人民政府 / 全国人大常委会公报',
    url: 'https://www.beijing.gov.cn/zhengce/zhengcefagui/qtwj/202609/t20260904_4850732.html', verificationStatus: 'verified', publishStatus: 'published',
    copyrightStatus: '法律类别与应对流程摘要并链接现行全文', note: '2024年修订文本自2024年11月1日起施行；用于突发事件分类、预防准备、监测预警、处置救援和恢复重建核对。',
  },
  {
    id: 'mem-production-safety-law-2021', sourceType: 'official_law', title: '中华人民共和国安全生产法（2021年修正）', organization: '中华人民共和国应急管理部',
    url: 'https://www.mem.gov.cn/fw/flfgbz/fg/202107/t20210716_416558.shtml', verificationStatus: 'verified', publishStatus: 'published',
    copyrightStatus: '法律职责摘要并链接法规全文', note: '用于生产经营单位主体责任、从业人员权利义务、安全监管与事故应急等基础核对。',
  },
  {
    id: 'state-council-government-information-disclosure', sourceType: 'official_law', title: '中华人民共和国政府信息公开条例（2019年修订）', organization: '中华人民共和国国务院',
    url: 'https://www.gc.gov.cn/columns/c366fb5a-39d1-482d-8611-28eda5f83252/202004/04/9e3c8b2f-d421-4a9c-8137-e93afff52a31.html', verificationStatus: 'verified', publishStatus: 'published',
    copyrightStatus: '法规制度摘要并链接全文', note: '用于政府信息主动公开、依申请公开和公开边界等制度框架核对；具体事项依现行条例处理。',
  },
  {
    id: 'npc-resident-committee-law', sourceType: 'official_law', title: '中华人民共和国城市居民委员会组织法', organization: '全国人民代表大会常务委员会 / 政府门户全文转载',
    url: 'https://www.xjhegs.gov.cn/xjhegs/c114406/202307/d6a22e164986411f8c0288da14b7d7f0.shtml', verificationStatus: 'verified', publishStatus: 'published',
    copyrightStatus: '基层自治制度摘要并链接法律全文', note: '用于居民委员会的基层群众性自治组织属性及其与政府派出机关的关系核对。',
  },
  {
    id: 'moj-production-safety-emergency-regulation', sourceType: 'official_law', title: '生产安全事故应急条例', organization: '国家行政法规库 / 司法部',
    url: 'https://xzfg.moj.gov.cn/mobile/law/detail?LawID=441', verificationStatus: 'verified', publishStatus: 'published',
    copyrightStatus: '法规职责摘要并链接全文', note: '用于生产安全事故风险辨识、应急预案编制、演练和应急响应的制度核对。',
  },
  {
    id: 'beijing-2026-work-report', sourceType: 'official_policy', title: '2026年北京市政府工作报告', organization: '北京市人民政府',
    url: 'https://www.beijing.gov.cn/cs/gncs/zcwj/202603/t20260327_4568183.html', verificationStatus: 'verified', publishStatus: 'published',
    copyrightStatus: '年度政策要点概述并链接报告原文', note: '用于北京年度任务和规划目标核对；报告目标不代表已经实现的结果。',
  },
  {
    id: 'mof-2026-budget-report', sourceType: 'official_policy', title: '关于2025年中央和地方预算执行情况与2026年中央和地方预算草案的报告', organization: '中华人民共和国财政部',
    url: 'https://www.mof.gov.cn/zhengwuxinxi/caizhengxinwen/202603/t20260316_3985331.htm', verificationStatus: 'verified', publishStatus: 'published',
    copyrightStatus: '预算制度与年度安排概述并链接报告原文', note: '用于一般公共预算、政府性基金预算、国有资本经营预算和社会保险基金预算的区分；数字只按对应年度与预算口径引用。',
  },
  {
    id: 'ndrc-15th-five-year-plan', sourceType: 'official_policy', title: '中华人民共和国国民经济和社会发展第十五个五年规划纲要（2026—2030年）', organization: '国家发展和改革委员会 / 全国人大',
    url: 'https://www.ndrc.gov.cn/fggz/fzzlgh/gjfzgh/202603/U020260317369114704096.pdf', verificationStatus: 'verified', publishStatus: 'published',
    copyrightStatus: '规划框架摘要并链接纲要全文', note: '2026—2030年国家规划纲要；区分战略目标、阶段任务、年度行动和已完成成果。',
  },
  {
    id: 'moe-senior-high-ideology-curriculum-2020', sourceType: 'official_reference', title: '普通高中思想政治等学科课程标准（2017年版2020年修订）发布通知', organization: '中华人民共和国教育部',
    url: 'https://hudong.moe.gov.cn/srcsite/A26/s8001/202006/t20200603_462199.html', verificationStatus: 'verified', publishStatus: 'published',
    copyrightStatus: '课程范围摘要并链接官方通知', note: '作为哲学、政治基础知识的课程范围参考；相关理论解释按课程标准和权威教材核对。',
  },
  {
    id: 'un-system-official', sourceType: 'official_reference', title: '联合国系统组成说明', organization: '联合国',
    url: 'https://www.un.org/en/about-us/un-system', verificationStatus: 'verified', publishStatus: 'published',
    copyrightStatus: '组织结构摘要并链接官方页面', note: '联合国系统包括联合国本身以及基金、方案、专门机构等实体；专门机构为与联合国建立关系的自治国际组织。',
  },
  {
    id: 'un-paris-agreement-ndc', sourceType: 'official_reference', title: '巴黎协定与国家自主贡献说明', organization: '联合国',
    url: 'https://www.un.org/en/climatechange/all-about-ndcs', verificationStatus: 'verified', publishStatus: 'published',
    copyrightStatus: '国际气候制度摘要并链接官方说明', note: '用于国家自主贡献（NDC）、五年更新周期、减缓和适应等知识核对；各国当期承诺须查看最新提交文本。',
  },
  {
    id: 'un-dppa-regional-organizations', sourceType: 'official_reference', title: '联合国与区域组织合作说明', organization: '联合国政治和建设和平事务部',
    url: 'https://dppa.un.org/en/node/133862', verificationStatus: 'verified', publishStatus: 'published',
    copyrightStatus: '组织关系摘要并链接官方说明', note: '用于理解《联合国宪章》第八章框架下联合国与区域组织在预防、调解和危机应对中的互补合作。',
  },
  {
    id: 'nhc-2026-health-work-report', sourceType: 'official_policy', title: '2026年全国卫生健康工作会议部署', organization: '中华人民共和国国家卫生健康委员会',
    url: 'https://www.nhc.gov.cn/bgt/c100022/202601/b638f0d4af094fbda637b18a26892926.shtml', verificationStatus: 'verified', publishStatus: 'published',
    copyrightStatus: '年度工作重点概述并链接官方发布', note: '用于卫生健康年度工作重点和服务体系建设核对；当年任务须与长期法律制度区分。',
  },
  {
    id: 'mee-2026-environment-work-report', sourceType: 'official_policy', title: '2026年全国生态环境保护工作报告', organization: '中华人民共和国生态环境部',
    url: 'https://www.mee.gov.cn/xxgk/hjyw/202601/t20260127_1142657.shtml', verificationStatus: 'verified', publishStatus: 'published',
    copyrightStatus: '年度政策方向摘要并链接工作报告', note: '用于污染治理、生态保护和绿色转型年度部署核对；规划目标与实际监测结果分开表述。',
  },
  {
    id: 'nda-2026-digital-society-work-points', sourceType: 'official_policy', title: '2026年数字社会发展工作要点', organization: '国家数据局',
    url: 'https://www.nda.gov.cn/sjj/ywpd/szsh/0519/20260519194939282443663_pc.html', verificationStatus: 'verified', publishStatus: 'published',
    copyrightStatus: '工作要点摘要并链接官方发布', note: '用于数字公共服务、智慧场景、数字治理和制度保障年度重点核对；规划任务不等于已全部落地。',
  },
  {
    id: 'most-2026-science-work-report', sourceType: 'official_policy', title: '全国科技工作会议关于2025年科技进展与2026年重点工作的报告', organization: '中华人民共和国科学技术部',
    url: 'https://www.most.gov.cn/kjbgz/202601/t20260127_195800.html', verificationStatus: 'verified', publishStatus: 'published',
    copyrightStatus: '科技工作方向摘要并链接官方报告', note: '用于年度科技议题核验；具体获奖、成果和应用状态须回到科技部或科研机构原始发布。',
  },
  {
    id: 'most-2025-science-awards', sourceType: 'official_reference', title: '2025年度国家科学技术奖获奖项目目录', organization: '中华人民共和国科学技术部',
    url: 'https://www.most.gov.cn/cxfw/kjjlcx/kjjl2025/202607/t20260708_196987.html', verificationStatus: 'verified', publishStatus: 'published',
    copyrightStatus: '成果类别与公布信息摘要并链接项目目录', note: '用于核对国家科学技术奖名称、年度和项目类别；获奖不等同于成果已大规模商业应用。',
  },
  {
    id: 'mohrss-2026-public-employment-services', sourceType: 'official_policy', title: '2026年全国公共就业招聘专项活动通知', organization: '中华人民共和国人力资源和社会保障部',
    url: 'https://www.mohrss.gov.cn/wap/zc/zcwj/202601/t20260120_565785.html', verificationStatus: 'verified', publishStatus: 'published',
    copyrightStatus: '就业服务工作要点摘要并链接官方通知', note: '用于公共就业服务、岗位对接和重点群体帮扶等年度政策核对；阶段性活动信息注明年份。',
  },
  {
    id: 'zhanhong-2025-mock-A类', sourceType: 'third_party_mock', title: '展鸿 2025 年浙江省考行测模拟卷 A 类', organization: '展鸿教育', examYear: 2025,
    url: 'https://static.32xueyuan.com/zq/u/cms/zj/202411/202048155177.pdf',
    answerUrl: 'https://zhanhong-32-read-able.oss-cn-hangzhou.aliyuncs.com/upload/videos/2024/11/02/%E5%B1%95%E9%B8%BF2025%E5%B9%B4%E6%B5%99%E6%B1%9F%E7%9C%81%E8%80%83%E3%80%8A%E8%A1%8C%E6%94%BF%E8%81%8C%E4%B8%9A%E8%83%BD%E5%8A%9B%E6%B5%8B%E9%AA%8C%E3%80%8B%E6%A8%A1%E6%8B%9F%E5%8D%B7110344187.pdf',
    verificationStatus: 'verified', publishStatus: 'published', copyrightStatus: '用户确认已获得转载授权',
    note: '第三方机构模拟题。本站题面按原卷原文录入，答案与解析按该卷答案部分核对。',
  },
  {
    id: 'zhanhong-2025-mock-B类', sourceType: 'third_party_mock', title: '展鸿 2025 年浙江省考行测模拟卷 B 类', organization: '展鸿教育', examYear: 2025,
    url: 'https://static.32xueyuan.com/zq/u/cms/zj/202411/202048155177.pdf',
    answerUrl: 'https://zhanhong-32-read-able.oss-cn-hangzhou.aliyuncs.com/upload/videos/2024/11/02/%E5%B1%95%E9%B8%BF2025%E5%B9%B4%E6%B5%99%E6%B1%9F%E7%9C%81%E8%80%83%E3%80%8A%E8%A1%8C%E6%94%BF%E8%81%8C%E4%B8%9A%E8%83%BD%E5%8A%9B%E6%B5%8B%E9%AA%8C%E3%80%8B%E6%A8%A1%E6%8B%9F%E5%8D%B7110344187.pdf',
    verificationStatus: 'verified', publishStatus: 'published', copyrightStatus: '用户确认已获得转载授权',
    note: '第三方机构模拟题。本站题面按原卷原文录入，答案与解析按该卷答案部分核对。',
  },
  {
    id: 'zhanhong-2025-mock-C类', sourceType: 'third_party_mock', title: '展鸿 2025 年浙江省考行测模拟卷 C 类', organization: '展鸿教育', examYear: 2025,
    url: 'https://static.32xueyuan.com/zq/u/cms/zj/202411/202048155177.pdf',
    answerUrl: 'https://zhanhong-32-read-able.oss-cn-hangzhou.aliyuncs.com/upload/videos/2024/11/02/%E5%B1%95%E9%B8%BF2025%E5%B9%B4%E6%B5%99%E6%B1%9F%E7%9C%81%E8%80%83%E3%80%8A%E8%A1%8C%E6%94%BF%E8%81%8C%E4%B8%9A%E8%83%BD%E5%8A%9B%E6%B5%8B%E9%AA%8C%E3%80%8B%E6%A8%A1%E6%8B%9F%E5%8D%B7110344187.pdf',
    verificationStatus: 'verified', publishStatus: 'published', copyrightStatus: '用户确认已获得转载授权',
    note: '第三方机构模拟题。本站题面按原卷原文录入，答案与解析按该卷答案部分核对。',
  },
  {
    id: 'zhanhong-jiangxi-2025-mock-1', sourceType: 'third_party_mock', title: '展鸿 2025 年江西省公务员录用考试模拟卷（一）《行测》', organization: '展鸿 / 32 学苑', examYear: 2025, region: '江西',
    url: 'https://static.32xueyuan.com/zq/u/cms/jx/202503/120855429qnm.pdf',
    answerUrl: 'https://static.32xueyuan.com/zq/u/cms/jx/202503/12085541lobk.pdf',
    verificationStatus: 'verified', publishStatus: 'published', copyrightStatus: '用户确认已获得转载授权',
    note: '题面、答案及解析按展鸿配套题本与解析 PDF 核对；本站已获转载授权。',
  },
  {
    id: 'zhanhong-jiangxi-2025-mock-3', sourceType: 'third_party_mock', title: '展鸿 2025 年江西省公务员录用考试模拟卷（三）《行测》', organization: '展鸿 / 32 学苑', examYear: 2025, region: '江西',
    url: 'https://static.32xueyuan.com/zq/u/cms/jx/202503/12085542c2xs.pdf',
    answerUrl: 'https://static.32xueyuan.com/zq/u/cms/jx/202503/051709044zd4.pdf',
    verificationStatus: 'verified', publishStatus: 'published', copyrightStatus: '用户确认已获得转载授权',
    note: '题面、答案及解析按展鸿配套题本与解析 PDF 核对；本站已获转载授权。',
  },
  {
    id: 'anhui-2022-zhanhong-qae', sourceType: 'recalled', title: '2022年安徽省公务员录用考试《行测》题（展鸿整理版）', organization: '展鸿教育 / 32 学苑', examYear: 2022, region: '安徽',
    url: 'https://static.32xueyuan.com/zq/u/cms/ah/202501/23111927qi0v.pdf',
    answerUrl: 'https://static.32xueyuan.com/zq/u/cms/ah/202501/23111927qi0v.pdf',
    verificationStatus: 'verified', publishStatus: 'published', copyrightStatus: '用户确认已获得转载授权',
    note: '110题题面、选项与解析来自同一整理版；图形及资料分析材料已核对。',
  },
  {
    id: 'zhanhong-2025-guangdong-mock-2', sourceType: 'third_party_mock', title: '展鸿 2025 年广东省公务员录用考试《行测》模拟卷（二）', organization: '展鸿教育', examYear: 2025, region: '广东',
    url: 'https://zhanhong-32-read-able.oss-cn-hangzhou.aliyuncs.com/upload/videos/2025/03/10/xc2163949910.pdf',
    answerUrl: 'https://zhanhong-32-read-able.oss-cn-hangzhou.aliyuncs.com/upload/videos/2025/03/10/xc2163949910.pdf',
    verificationStatus: 'verified', publishStatus: 'published', copyrightStatus: '用户确认已获得转载授权',
    note: '100题题面、答案与解析按配套卷逐题核验；95道单选题已接入，5道多选题暂缓。',
  },
  {
    id: 'gkzhenti-2026-jiangxi', sourceType: 'recalled', title: '2026年江西省公务员录用考试《行测》题（网友回忆版）', organization: '爱真题 / 公开真题库（题面、答案键及公开解析归档）', examYear: 2026, region: '江西',
    url: 'https://www.aipta.com/article/10594.html',
    answerUrl: 'https://gwy.gkzhenti.cn/answer/1775360736151', verificationStatus: 'verified', publishStatus: 'published',
    copyrightStatus: '用户确认已获得转载授权',
    note: '题面按爱真题公开回忆版核定，答案键与公开真题库1–130题逐题一致；保留网友回忆版标注。',
  },
  {
    id: 'jiangsu-2024-a-32xueyuan', sourceType: 'verified_exam', title: '2024 年江苏省公务员录用考试行测 A 类真题（第三方出版原卷）', organization: '32 学苑', examYear: 2024,
    url: 'https://static.32xueyuan.com/zq//u/cms/zj/202411/221409378lxq.pdf',
    answerUrl: 'https://static.32xueyuan.com/zq//u/cms/zj/202411/221409378lxq.pdf',
    verificationStatus: 'verified', publishStatus: 'published', copyrightStatus: '用户确认已获得转载授权',
    note: '题面和出版版答案解析来自同一 PDF；各模块仅开放题面及答案解析完整的题目。',
  },
  {
    id: 'zhejiang-2023-a-recall', sourceType: 'recalled', title: '2023 年浙江省考行测 A 卷公开回忆题', organization: 'Aipta 题库 / 32 学苑答案解析', examYear: 2023,
    url: 'https://www.aipta.com/article/3524.html',
    answerUrl: 'https://static.32xueyuan.com/zq//u/cms/zj/202310/20144954ob39.pdf',
    verificationStatus: 'verified', publishStatus: 'published', copyrightStatus: '用户确认已获得转载授权',
    note: '题面来自公开考生回忆题页，答案及解析按出版版 PDF 核对；未拆清图像素材的题继续留在归档。',
  },
];
