export const GENERAL_KNOWLEDGE_SOURCES = [
  {
    id: 'gwy-2026-outline', sourceType: 'official_outline_example', title: '中央机关及其直属机构2026年度考试录用公务员公共科目笔试考试大纲',
    organization: '国家公务员局（国家林业和草原局政府网转载）', examYear: 2026,
    url: 'https://www.forestry.gov.cn/c/www/gsgg/645383.jhtml', verificationStatus: 'verified',
    publishStatus: 'published', copyrightStatus: '题意重述；不复制长题干',
    note: '大纲将常识判断列为独立部分，并公开三道常识例题。题目在本站以短题意重述呈现，不标为正式真题。',
  },
  {
    id: 'npc-civil-code', sourceType: 'official_law', title: '中华人民共和国民法典', organization: '全国人民代表大会 / 国家法律法规数据库',
    url: 'https://flk.npc.gov.cn/detail2.html', verificationStatus: 'verified', publishStatus: 'published',
    copyrightStatus: '法规事实摘述并链接原文', note: '涉及具体法律条文时以国家法律法规数据库的有效文本为准。',
  },
  {
    id: 'npc-constitution', sourceType: 'official_law', title: '中华人民共和国宪法', organization: '全国人民代表大会 / 国家法律法规数据库',
    url: 'https://flk.npc.gov.cn/detail2.html', verificationStatus: 'verified', publishStatus: 'published',
    copyrightStatus: '法规事实摘述并链接原文', note: '用于公民权利义务知识；引用时核对现行有效版本。',
  },
  {
    id: 'npc-law-database', sourceType: 'official_law', title: '国家法律法规数据库', organization: '全国人大常委会办公厅',
    url: 'https://flk.npc.gov.cn/', verificationStatus: 'verified', publishStatus: 'published',
    copyrightStatus: '法规事实摘述并链接原文', note: '法律时效核验主入口。题库不替代对最新法律文本的查询。',
  },
  {
    id: 'railway-high-speed-design', sourceType: 'official_reference', title: '《高速铁路设计规范》专家解读', organization: '国家铁路局',
    url: 'https://source.nra.gov.cn/xxgk/gkml/ztjg/gfzd/zcjd/202204/t20220405_280609.shtml',
    verificationStatus: 'verified', publishStatus: 'published', copyrightStatus: '技术事实概述并链接原文',
    note: '国家铁路局说明高速铁路规范中的无砟轨道结构、轨道稳定性和平顺性要求；题目为本站独立编写。',
  },
  {
    id: 'lunar-eclipse-science', sourceType: 'official_reference', title: '月全食与“红月亮”', organization: '中国科学院紫金山天文台',
    url: 'https://pmo.cas.cn/xwdt2019/kpdt2019/201909/t20190915_5385983.html',
    verificationStatus: 'verified', publishStatus: 'published', copyrightStatus: '科学事实概述并链接原文',
    note: '紫金山天文台解释月全食期间地球大气折射长波段光进入本影，月面呈微红或古铜色。',
  },
  {
    id: 'thermal-printing-science', sourceType: 'official_reference', title: '热敏纸显色原理', organization: '江华瑶族自治县科学技术协会 / 县人民政府',
    url: 'https://jh.gov.cn/jh/kpjh/202411/494c6fff7e1c41b8a7671a4517ec0f11.shtml',
    verificationStatus: 'verified', publishStatus: 'published', copyrightStatus: '科学事实概述并链接原文',
    note: '政府科普页面介绍热敏涂层受热后的显色反应；题目为本站独立编写，不采用原题面。',
  },
  {
    id: 'admin-penalty-law-2021', sourceType: 'official_law', title: '中华人民共和国行政处罚法（2021年修订）', organization: '工业和信息化部政府门户网站',
    url: 'https://www.miit.gov.cn/zwgk/zcwj/flfg/art/2022/art_76d37c09bd594d67b80ec2aa6fababcc.html',
    verificationStatus: 'verified', publishStatus: 'published', copyrightStatus: '法规事实摘述并链接法规全文',
    note: '官方全文载明2021年修订文本及第三十三、第四十四、第四十五、第六十二条；2021年7月15日起施行。',
  },
  {
    id: 'admin-reconsideration-law-2023', sourceType: 'official_law', title: '中华人民共和国行政复议法（2023年修订）', organization: '中国人大网原文（生态环境部转载）',
    url: 'https://www.mee.gov.cn/home/ztbd/2022/sthjpf/fgbzjd/202309/t20230914_1040873.shtml',
    verificationStatus: 'verified', publishStatus: 'published', copyrightStatus: '法规事实摘述并链接法规全文',
    note: '全国人大原文转载；2023年9月1日修订、2024年1月1日起施行，第二十条规定通常的六十日申请期限及例外。',
  },
  {
    id: 'beijing-12345-regulation', sourceType: 'official_policy', title: '北京市接诉即办工作条例', organization: '北京市人民代表大会常务委员会 / 首都之窗',
    url: 'https://www.beijing.gov.cn/zhengce/dfxfg/202109/t20210925_2501573.html', verificationStatus: 'verified',
    publishStatus: 'published', copyrightStatus: '法规事实摘述并链接原文', note: '政府门户页面标示本条例自2021-09-24施行、现行有效；使用前仍需复核状态。',
  },
  {
    id: 'gov-2026-work-report', sourceType: 'official_policy', title: '2026年政府工作报告', organization: '国务院',
    url: 'https://big5.www.gov.cn/gate/big5/www.gov.cn/yaowen/liebiao/202603/content_7062625.htm',
    verificationStatus: 'verified', publishStatus: 'published', copyrightStatus: '政策事实概述并链接原文',
    note: '时政内容保留年度标签；该条只表示报告资料来源，不代表下一年度仍适用。',
  },
  {
    id: 'beijing-master-plan', sourceType: 'official_policy', title: '北京城市总体规划与城市空间资料', organization: '北京市人民政府',
    url: 'https://www.beijing.gov.cn/', verificationStatus: 'pending', publishStatus: 'reference_only',
    copyrightStatus: '待定位具体现行规划文本', note: '当前仅作后续核对入口；相应知识点不作为已核验的空间细节题。',
  },
  {
    id: 'mmee-carbon-neutral', sourceType: 'official_policy', title: '碳达峰碳中和与生态环境公开资料', organization: '生态环境部',
    url: 'https://www.mee.gov.cn/', verificationStatus: 'pending', publishStatus: 'reference_only',
    copyrightStatus: '待定位具体政策/技术文本', note: '目录入口，后续发布具体双碳数据前须定位正式文件。',
  },
  {
    id: 'stats-cpi', sourceType: 'official_statistics', title: '国家统计局居民消费价格指数资料', organization: '国家统计局',
    url: 'https://www.stats.gov.cn/', verificationStatus: 'pending', publishStatus: 'reference_only',
    copyrightStatus: '统计口径待逐题标注', note: '知识讲解说明CPI概念，不使用未核验的年度数值。',
  },
  {
    id: 'unesco-solar-terms', sourceType: 'official_reference', title: '二十四节气（人类非物质文化遗产）', organization: '联合国教科文组织',
    url: 'https://ich.unesco.org/en/RL/knowledge-of-the-times-and-practices-concerning-the-twenty-four-solar-terms-00647',
    verificationStatus: 'verified', publishStatus: 'published', copyrightStatus: '事实概述并链接原文',
    note: '用于节气的文化遗产身份与基础解释，不复用第三方题库题干。',
  },
  {
    id: 'gov-ai-guidance', sourceType: 'official_reference', title: '人工智能与数据治理公开政策索引', organization: '国家互联网信息办公室',
    url: 'https://www.cac.gov.cn/', verificationStatus: 'pending', publishStatus: 'reference_only',
    copyrightStatus: '待定位具体现行文件', note: '未定位具体文件前只讲稳定基础概念，不发布法规时效判断。',
  },
  {
    id: 'party-history-public', sourceType: 'official_reference', title: '中国共产党历史和改革开放权威资料索引', organization: '中共中央党史和文献研究院',
    url: 'https://www.dswxyjy.org.cn/', verificationStatus: 'pending', publishStatus: 'reference_only',
    copyrightStatus: '待定位具体资料条目', note: '仅作内容核对入口；不发布未经逐项核实的具体时间题。',
  },
  {
    id: 'economics-intro-reference', sourceType: 'official_reference', title: '基础经济学术语参考索引', organization: '本站编写团队',
    url: 'https://www.stats.gov.cn/', verificationStatus: 'reviewed', publishStatus: 'published',
    copyrightStatus: '本站原创讲解', note: '用于稳定的基础经济学概念；不包含特定年度统计数据。',
  },
  {
    id: 'marxism-public-reference', sourceType: 'official_reference', title: '马克思主义哲学基础公开学习资料索引', organization: '中国社会科学院 / 公开理论资料',
    url: 'https://www.cssn.cn/', verificationStatus: 'pending', publishStatus: 'reference_only',
    copyrightStatus: '待定位具体出处', note: '索引入口；相关理论简述仍需补充具体权威材料和逐条复核。',
  },
  {
    id: 'offcn-public-mock-index', sourceType: 'third_party_mock', title: '中公教育公开模拟题页面（来源索引）', organization: '中公教育',
    url: 'https://xzgwy.offcn.com/2020/xc_0526/25734_7.html', verificationStatus: 'reviewed',
    publishStatus: 'reference_only', copyrightStatus: '题面展示授权未核实',
    note: '页面可访问不等于获得复制授权。暂不收录其题干，后续仅在取得授权或确认许可后作为练习题。',
  },
  {
    id: 'gaodun-shanghai-mock-index', sourceType: 'third_party_mock', title: '高顿公考上海市考模拟卷页面（来源索引）', organization: '高顿公考',
    url: 'https://gk.gaodun.com/shanghai/gongwuyuan/xingce/1540.html', verificationStatus: 'reviewed',
    publishStatus: 'reference_only', copyrightStatus: '题面展示授权未核实',
    note: '作为后续真题类型和题源调查索引，不将网页可访问误作题目开放许可。',
  },
  {
    id: 'anhui-2026-outline', sourceType: 'official_outline_example', title: '安徽省2026年度公务员笔试考试大纲（公开例题）', organization: '安徽省人力资源和社会保障厅 / 淮南市人力资源和社会保障局',
    url: 'https://rsj.huainan.gov.cn/group4/M00/11/14/rB40qWlooVmAFWHRAA3nByKSHRA495.pdf?attachDownload=1', verificationStatus: 'verified',
    publishStatus: 'published', copyrightStatus: '例题摘要改写并链接官方大纲', note: '覆盖政治理论、常识判断、言语、数量、判断推理和资料分析公开例题；图片题因图像未随文字抽取而未纳入。',
  },
  {
    id: 'zhejiang-2025a-recall', sourceType: 'recalled', title: '2025年浙江省公务员考试《行测》A类回忆版及答案', organization: '公开真题库 / 考生回忆资料',
    url: 'https://gwy.gkzhenti.cn/paper/1739531137130', answerUrl: 'https://gwy.gkzhenti.cn/answer/1739531137130', verificationStatus: 'verified',
    publishStatus: 'published', copyrightStatus: '题意与选项摘要改写并注明回忆来源', note: '仅发布题面资源完整、答案可核的分项；Q12依赖未取得的路线图，继续暂缓。公开答案页用于核对答案，不代表官方命题文件。',
  },
  {
    id: 'mofcom-emergency-supplies', sourceType: 'official_policy', title: '生活必需品市场供应应急管理相关规定', organization: '中华人民共和国商务部',
    url: 'https://www.mofcom.gov.cn/zcfb/blgg/art/2011/art_9c44dbc882cd47a2a2db6ddd07e242fd.html', verificationStatus: 'verified', publishStatus: 'published',
    copyrightStatus: '政策事实概述并链接原文', note: '用于应急组织货源、储备投放和生活必需品市场供应管理的基础概念。',
  },
  {
    id: 'ndrc-three-distributions', sourceType: 'official_policy', title: '促进共同富裕与三次分配的政策解读', organization: '国家发展和改革委员会',
    url: 'https://www.ndrc.gov.cn/fggz/jyysr/jysrsbxf/202109/t20210924_1297384_ext.html', verificationStatus: 'verified', publishStatus: 'published',
    copyrightStatus: '政策事实概述并链接原文', note: '用于区分初次分配、再分配和第三次分配的主体与机制。',
  },
  {
    id: 'npc-oath-decision', sourceType: 'official_law', title: '关于实行宪法宣誓制度的决定', organization: '全国人民代表大会常务委员会',
    url: 'https://www.npc.gov.cn/npc/c2/c30834/202306/t20230606_429893.html', verificationStatus: 'verified', publishStatus: 'published',
    copyrightStatus: '法条事实摘述并链接原文', note: '宣誓适用对象和组织程序以现行法律决定为准。',
  },
  {
    id: 'court-judge-oath-rules', sourceType: 'official_law', title: '中华人民共和国法官宣誓组织办法', organization: '最高人民法院',
    url: 'https://www.court.gov.cn/fabu/xiangqing/20262.html', verificationStatus: 'verified', publishStatus: 'published',
    copyrightStatus: '规则事实摘述并链接原文', note: '用于核对法院系统法官职务宣誓的组织安排。',
  },
  {
    id: 'cpc-20th-report', sourceType: 'official_policy', title: '中国共产党第二十次全国代表大会报告', organization: '中国政府网',
    url: 'https://app.www.gov.cn/govdata/gov/202210/25/493662/article.html', verificationStatus: 'verified', publishStatus: 'published',
    copyrightStatus: '政策观点概述并链接原文', note: '用于核对城乡融合、发展与公平及生态文明等稳定政策表述。',
  },
  {
    id: 'beijing-willow-fluff', sourceType: 'official_reference', title: '杨柳飞絮与植物种子传播科普', organization: '北京市园林绿化局',
    url: 'https://yllhj.beijing.gov.cn/ztxx/zlylfxgcyjhj/ylfxqy/201510/t20151013_119733.shtml', verificationStatus: 'verified', publishStatus: 'published',
    copyrightStatus: '科学事实概述并链接原文', note: '说明杨柳飞絮与种子绒毛及风力传播之间的关系。',
  },
  {
    id: 'pku-capsaicin-chemistry', sourceType: 'official_reference', title: '辣椒素溶解性与生活化学实验研究', organization: '北京大学《大学化学》',
    url: 'https://www.dxhx.pku.edu.cn/fileup/1000-8438/PDF/dxhx-201803041.pdf', verificationStatus: 'verified', publishStatus: 'published',
    copyrightStatus: '科学事实概述并链接论文', note: '用于核对辣椒素在水、乙醇等介质中的溶解性。',
  },
  {
    id: 'nra-railway-track', sourceType: 'official_reference', title: '高速铁路设计规范专家解读', organization: '国家铁路局',
    url: 'https://source.nra.gov.cn/xxgk/gkml/ztjg/gfzd/zcjd/202204/t20220405_280609.shtml', verificationStatus: 'verified', publishStatus: 'published',
    copyrightStatus: '技术事实概述并链接原文', note: '用于高速铁路轨道结构与线路基础知识；无缝线路仍须考虑温度变化。',
  },
  {
    id: 'moe-employment-priority', sourceType: 'official_policy', title: '高校毕业生等青年就业服务与支持政策', organization: '教育部',
    url: 'https://www.moe.gov.cn/jyb_xxgk/moe_1777/moe_1778/202409/t20240926_1153200.html', verificationStatus: 'verified', publishStatus: 'published',
    copyrightStatus: '政策事实概述并链接原文', note: '用于就业服务、重点群体支持和技能提升等知识点。',
  },
  {
    id: 'mct-transaction-costs', sourceType: 'official_policy', title: '降低制度性交易成本相关政策解读', organization: '文化和旅游部转载国务院办公厅材料',
    url: 'https://www.mct.gov.cn/preview/whhlyqyzcxxfw/yshjxf/202306/t20230612_944383.html', verificationStatus: 'verified', publishStatus: 'published',
    copyrightStatus: '政策事实概述并链接原文', note: '用于区分制度规则及流程带来的成本与企业正常生产投入。',
  },
  {
    id: 'politburo-20240926', sourceType: 'official_policy', title: '中共中央政治局会议研究当前经济形势和经济工作', organization: '新华社',
    url: 'https://www.xinhuanet.com/fortune/20240926/0f9a6b9e501c48ea85aea3b6d8cc7ccc/c.html', verificationStatus: 'verified', publishStatus: 'published',
    copyrightStatus: '政策事实概述并链接原文', note: '用于核对2024年9月26日会议关于扩大内需、逆周期调节和民生工作的表述。',
  },
  {
    id: 'pbc-lpr', sourceType: 'official_reference', title: '贷款市场报价利率形成机制与公布资料', organization: '中国人民银行',
    url: 'https://www.pbc.gov.cn/zhengcehuobisi/125207/125213/125440/125832/2804873/index.html', verificationStatus: 'verified', publishStatus: 'published',
    copyrightStatus: '机制事实概述并链接原文', note: '用于LPR的报价、公布和贷款定价传导知识。',
  },
  {
    id: 'ethnic-autonomy-law', sourceType: 'official_law', title: '中华人民共和国民族区域自治法', organization: '司法部行政复议行政应诉局法规公开平台',
    url: 'https://xzfy.moj.gov.cn/c/2021-01-06/487588.shtml', verificationStatus: 'verified', publishStatus: 'published',
    copyrightStatus: '法条事实摘述并链接原文', note: '用于核对自治地方、自治机关及主要负责人的法定规定。',
  },
  {
    id: 'palace-history', sourceType: 'official_reference', title: '故宫博物院院史与紫禁城沿革', organization: '故宫博物院',
    url: 'https://www.dpm.org.cn/subject_600/index.html', verificationStatus: 'verified', publishStatus: 'published',
    copyrightStatus: '历史事实概述并链接原文', note: '用于核对紫禁城营建、明清皇宫及故宫博物院沿革。',
  },
  {
    id: 'most-salt-tolerant-rice', sourceType: 'official_reference', title: '耐盐碱水稻研究与示范应用', organization: '科学技术部',
    url: 'https://www.most.gov.cn/dfkj/hain/zxdt/202203/t20220323_179960.html', verificationStatus: 'verified', publishStatus: 'published',
    copyrightStatus: '科技事实概述并链接原文', note: '用于说明耐盐碱品种及其土壤、水分和栽培条件。',
  },
  {
    id: 'spacecraft-battery-upgrade', sourceType: 'official_reference', title: '神舟飞船储能电池技术升级', organization: '中国航天科技集团有限公司',
    url: 'https://www.spacechina.com/n25/n2014789/n2014809/c4217099/content.html', verificationStatus: 'verified', publishStatus: 'published',
    copyrightStatus: '科技事实概述并链接原文', note: '官方资料说明神舟十八号起主电源储能电池由镉镍体系改为锂离子体系。',
  },
  {
    id: 'hangzhou-2022-flame', sourceType: 'official_reference', title: '杭州亚运会火种采集于良渚古城遗址', organization: '杭州第19届亚运会组委会',
    url: 'https://www.hangzhou2022.cn/xwzx/jdxw/ttxw/202306/t20230615_62401.shtml', verificationStatus: 'verified', publishStatus: 'published',
    copyrightStatus: '事实概述并链接原文', note: '用于区分良渚遗址与河姆渡遗址及亚运会火种采集地点。',
  },
  {
    id: 'lantern-festival-poem', sourceType: 'official_reference', title: '元宵节诗词文本参考', organization: '中国哲学书电子化计划',
    url: 'https://ctext.org/text.pl?if=gb&node=208579', verificationStatus: 'reviewed', publishStatus: 'published',
    copyrightStatus: '古典作品出处并链接原文', note: '用于核对“正月中旬”“灯市”等诗词线索与元宵节的关系。',
  },
  {
    id: 'unesco-liangzhu', sourceType: 'official_reference', title: '良渚古城遗址世界遗产资料', organization: '联合国教科文组织世界遗产中心',
    url: 'https://whc.unesco.org/en/list/1592/', verificationStatus: 'verified', publishStatus: 'published',
    copyrightStatus: '遗产事实概述并链接原文', note: '用于核对良渚古城的考古、社会组织与世界遗产信息。',
  },
  {
    id: 'china-fire-gas-safety', sourceType: 'official_reference', title: '燃气泄漏时的家庭安全处置', organization: '国家消防救援局',
    url: 'https://www.119.gov.cn/kp/hzyf/jt/2022/1201.shtml', verificationStatus: 'verified', publishStatus: 'published',
    copyrightStatus: '安全事实概述并链接原文', note: '燃气泄漏时不要操作电器开关或产生火花，应按消防部门指引通风、撤离并求助。',
  },
  {
    id: 'beijing-political-consultation-regulation', sourceType: 'official_policy', title: '中国共产党政治协商工作条例', organization: '中共中央 / 首都之窗',
    url: 'https://www.beijing.gov.cn/zhengce/zhengcefagui/202206/t20220621_2747230.html', verificationStatus: 'verified', publishStatus: 'published',
    copyrightStatus: '政策规则概述并链接原文', note: '条例区分政党协商与人民政协政治协商，并列明两类协商的对象。',
  },
  {
    id: 'beijing-2023-recall', sourceType: 'recalled', title: '2023年北京市公务员录用考试《行测》真题（考生回忆版）',
    organization: '星光公考（题面回忆整理）；拉西学习资源站（答案解析，标注来源为1mi.xyz）', examYear: 2023, region: '北京',
    url: 'https://upload.xingguanggongkao.com/pdf/2023%E5%B9%B4%E5%8C%97%E4%BA%AC%E5%B8%82%E5%85%AC%E5%8A%A1%E5%91%98%E5%BD%95%E7%94%A8%E8%80%83%E8%AF%95%E3%80%8A%E8%A1%8C%E6%B5%8B%E3%80%8B%E7%9C%9F%E9%A2%98%EF%BC%88%E8%80%83%E7%94%9F%E5%9B%9E%E5%BF%86%E7%89%88%EF%BC%89.pdf?time=1733730281',
    answerUrl: 'https://lasee.net/gongwuyuan/167886579811619.html', verificationStatus: 'verified', publishStatus: 'published',
    copyrightStatus: 'adapted_public_source', note: '题面与答案分别由公开回忆 PDF 和答案解析页核验；本站仅发布题意改述的常识第1–14、16题。第15题缺失，整卷有缺题且非官方原卷。',
  },
  {
    id: 'moe-history-curriculum-2022', sourceType: 'official_reference', title: '义务教育历史课程标准（2022年版）', organization: '中华人民共和国教育部',
    url: 'https://www.moe.gov.cn/srcsite/A26/s8001/202204/W020220420582345700037.pdf', verificationStatus: 'verified', publishStatus: 'published',
    copyrightStatus: '课程范围与历史事实概述并链接原文', note: '用于历史时期、重大事件、制度与历史时序方法的基础核对。',
  },
  {
    id: 'cpc-history-volume-one', sourceType: 'official_reference', title: '中国共产党历史·第一卷（1921—1949）', organization: '中共中央党史和文献研究院 / 中共党史出版社',
    url: 'https://www.dswxyjy.org.cn/n1/2019/0627/c427919-31199220.html', verificationStatus: 'verified', publishStatus: 'published',
    copyrightStatus: '历史事实概述并链接权威出版资料', note: '用于鸦片战争以来近代史、辛亥革命、五四运动和中国共产党成立等时间线核对。',
  },
  {
    id: 'moe-chinese-textbook-intro', sourceType: 'official_reference', title: '普通高中语文教材介绍', organization: '中华人民共和国教育部',
    url: 'https://www.moe.gov.cn/fbh/live/2019/51084/sfcl/201908/t20190827_395974.html', verificationStatus: 'verified', publishStatus: 'published',
    copyrightStatus: '课程选文范围概述并链接原文', note: '用于古典诗文、文学体裁和中国文学史常见脉络的学习参考。',
  },
  {
    id: 'unesco-intangible-china', sourceType: 'official_reference', title: '中国非物质文化遗产名录条目', organization: '联合国教科文组织',
    url: 'https://ich.unesco.org/en/state/china-CN?info=elements-on-the-lists', verificationStatus: 'verified', publishStatus: 'published',
    copyrightStatus: '遗产项目事实概述并链接原文', note: '用于核对中国列入 UNESCO 非物质文化遗产名录的戏曲、节庆、书法和传统工艺项目。',
  },
  {
    id: 'unesco-ich-convention', sourceType: 'official_reference', title: '保护非物质文化遗产公约', organization: '联合国教科文组织',
    url: 'https://ich.unesco.org/en/convention', verificationStatus: 'verified', publishStatus: 'published',
    copyrightStatus: '公约定义与领域概述并链接原文', note: '用于非物质文化遗产的社区认定、代际传承、活态变化及主要领域。',
  },
  {
    id: 'unesco-peking-opera', sourceType: 'official_reference', title: '京剧（人类非物质文化遗产）', organization: '联合国教科文组织',
    url: 'https://ich.unesco.org/en/RL/peking-opera-00418', verificationStatus: 'verified', publishStatus: 'published',
    copyrightStatus: '艺术形式事实概述并链接原文', note: '用于京剧唱、念、做、打及象征性舞台表达等知识。',
  },
  {
    id: 'unesco-kunqu-opera', sourceType: 'official_reference', title: '昆曲（人类非物质文化遗产）', organization: '联合国教科文组织',
    url: 'https://ich.unesco.org/en/RL/kun-qu-opera-00004', verificationStatus: 'verified', publishStatus: 'published',
    copyrightStatus: '艺术形式事实概述并链接原文', note: '用于昆曲形成地域、历史时期和表演特点核对。',
  },
  {
    id: 'unesco-xuan-paper', sourceType: 'official_reference', title: '宣纸传统制作技艺（人类非物质文化遗产）', organization: '联合国教科文组织',
    url: 'https://ich.unesco.org/en/RL/traditional-handicrafts-of-making-xuan-paper-00201', verificationStatus: 'verified', publishStatus: 'published',
    copyrightStatus: '工艺事实概述并链接原文', note: '用于宣纸原料、产地、制作技艺和书画用途核对。',
  },
  {
    id: 'unesco-timber-craft', sourceType: 'official_reference', title: '中国传统木结构营造技艺', organization: '联合国教科文组织',
    url: 'https://ich.unesco.org/en/RL/chinese-traditional-architectural-craftsmanship-for-timber-framed-structures-00223', verificationStatus: 'verified', publishStatus: 'published',
    copyrightStatus: '建筑技艺事实概述并链接原文', note: '用于传统木结构建筑与营造技艺的活态传承知识。',
  },
  {
    id: 'unesco-world-heritage-faq', sourceType: 'official_reference', title: '世界遗产文化、自然与混合类别说明', organization: '联合国教科文组织世界遗产中心',
    url: 'https://whc.unesco.org/en/faq/319', verificationStatus: 'verified', publishStatus: 'published',
    copyrightStatus: '公约类别事实概述并链接原文', note: '用于区分文化遗产、自然遗产和兼具两类价值的混合遗产。',
  },
  {
    id: 'icom-museum-definition', sourceType: 'official_reference', title: '国际博物馆协会博物馆定义（2022）', organization: '国际博物馆协会',
    url: 'https://icom.museum/en/resources/standards-guidelines/museum-definition/', verificationStatus: 'verified', publishStatus: 'published',
    copyrightStatus: '机构定义概述并链接原文', note: '用于博物馆的研究、收藏、保护、诠释、展示与教育服务等职能。',
  },
  {
    id: 'met-art-history-education', sourceType: 'official_reference', title: '世界艺术史与宗教艺术教育资料', organization: '大都会艺术博物馆',
    url: 'https://resources.metmuseum.org/resources/metpublications/pdf/The_Art_of_South_and_Southeast_Asia_A_Resource_for_Educators.pdf', verificationStatus: 'verified', publishStatus: 'published',
    copyrightStatus: '艺术与宗教基础事实概述并链接教育资料', note: '用于世界艺术史、南亚宗教艺术及文化语境的基础学习。',
  },
  {
    id: 'met-renaissance-art', sourceType: 'official_reference', title: '文艺复兴欧洲艺术教育资料', organization: '大都会艺术博物馆',
    url: 'https://www.metmuseum.org/-/media/files/learn/for-educators/publications-for-educators/renaissance.pdf', verificationStatus: 'verified', publishStatus: 'published',
    copyrightStatus: '艺术史事实概述并链接原文', note: '用于文艺复兴时期欧洲艺术、人物与事件背景核对。',
  },
  {
    id: 'met-ancient-greece-art', sourceType: 'official_reference', title: '古希腊艺术史时间线', organization: '大都会艺术博物馆',
    url: 'https://www.metmuseum.org/pt/toah/ht/04/eusb', verificationStatus: 'verified', publishStatus: 'published',
    copyrightStatus: '艺术史事实概述并链接原文', note: '用于古希腊几何、古风、古典与希腊化时期艺术的时序核对。',
  },
  {
    id: 'met-world-religions', sourceType: 'official_reference', title: '南亚与东南亚宗教艺术教育资料', organization: '大都会艺术博物馆',
    url: 'https://resources.metmuseum.org/resources/metpublications/pdf/The_Art_of_South_and_Southeast_Asia_A_Resource_for_Educators.pdf', verificationStatus: 'verified', publishStatus: 'published',
    copyrightStatus: '宗教与艺术基础知识概述并链接教育资料', note: '用于印度教、佛教、耆那教与伊斯兰艺术的地域和文化语境参考。',
  },
];
